### ISSUE TITLE
improving the header, cards, footer and adding dark mode

### ISSUE THREAD

**Issue by pbpcodes** [DSC-JSS-NOIDA/foss-events#101]
Hey. I am a GSSoC'21 participant. I would like to contribute to the project by adding the following things to the website: 

**1) Improving the header style and adding for buttons with functionality.
2) Improving the cards style and adding "change color during hover" functionality.
3) Improving the footer with more info.
4) Adding dark mode to the website.**

Please assign me this project.

**Comment by SARVESHKHANDELWAL** [comment]
Why this issues are not label as GSSOC ???
I would like to work on this issue,can you assign me?

**Comment by oneknucklehead** [comment]
I can improve the header style and add the button with functionality and I can also improve the style of the cards and add the change hover color functionality. Can you please assign this issue to me?

**Comment by 0Faiz0** [comment]
i can do this work and can make that better.

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give a hand in this project. Please assign this issue to me.
