### ISSUE TITLE
Create home page 

### ISSUE THREAD

**Issue by kumarishalini6** [DSC-JSS-NOIDA/foss-events#103]
1.**there should be a home page through which we can render on  main page**

I want to add home.html to make project more attractive and in home.html there will be a button which is rendering you in main page. 
footer should be more attractive 

i want to work on it under gssoc21, can you please assign it to me??

**Comment by MayankBeck** [comment]
I would like to work on this issue under GSSoC 21. Can you please assign this to me ?

**Comment by oneknucklehead** [comment]
I want to work on this issue under GSSoC '21. I can add the home page and make the page more attractive and render it to the main page.

**Comment by sushant1824** [comment]
i am interested in this . i am experienced in wordpress and its plugin and also have knowledge of html and css. so can u assign me

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
