### ISSUE TITLE
Add favicon.

### ISSUE THREAD

**Issue by padmajabhol** [DSC-JSS-NOIDA/foss-events#106]
**Is your feature request related to a problem? Please describe.**
Unlike other websites, this does not have a favicon.

**Describe the solution you'd like**
Creating a theme based favicon.

**Comment by sagunjaiswal** [comment]
hi,
I would love to add the favicon please assign this to me.
thanks in advance

**Comment by gritika18** [comment]
I would love to add a favicon. Could you please assign this to me?

**Comment by pshivesh8** [comment]
GSSOC'21
I would like to contribute to this issue. could you please assign it?

**Comment by vanshikapandey** [comment]
Sir I can take this issue and work on it please assign it to me

**Comment by SwatiPriya2805** [comment]
I am a GSSoC'21 participant.
I would like to work on this issue. I would be thankful if you can assign this issue to me.
