### ISSUE TITLE
Changing a button's color on hover

### ISSUE THREAD

**Issue by priyanshupardhi** [DSC-JSS-NOIDA/foss-events#109]
**It would be great if the color of the "More Info" button change on hovering over it.**
I want the "More Info" to change its background color new color on hover

**It can be resolved by changing CSS**
I will be using ":hover" selector to select the button when the user mouse over them, I will change its background-color 

@rudrakshi99 I would like to work on this issue, please assign me.

![Color change](https://cdn1.bbcode0.com/uploads/2021/3/10/91ae1fccca68a5377f4ac5c6ab9111dc-full.jpg)

**Comment by ayu222220** [comment]
Would like to work on this will try to change the color according to the  site theme and use some lighter or darker color accordingly using CSS with the feature of hover.

**Comment by kirtirajsinh** [comment]
I would like to contribute to this issue.  could you please assign it.

**Comment by SARVESHKHANDELWAL** [comment]
I would like to contribute to this issue ,can you please assign me.

**Comment by pshivesh8** [comment]
GSSOC'21
I would like to contribute to this issue. could you please assign it?

**Comment by simranbhalla3** [comment]
Hii I am Simran Bhalla, a Gssoc'21 Participant. Project admins please consider this issue for gssoc21 label and assign this issue to me.

**Comment by 0Faiz0** [comment]
I would like to contribute on this project, Project admin will you please assign this issue to me.
GSSOC'21

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by tanyalava** [comment]
I am a GSSoC'21 participant and would really like to work on this issue . I will make it look better .

**Comment by aroma-sketch** [comment]
hey there, I am new to open source projects, and I would like to solve this issue as a small step, looking ahead to a response. it would be helpful.

**Comment by fatma-sia27** [comment]
Hello , Iam new to open source contribution so I would be great if you assign me this project to me. I had learned CSS and HTML recently so pleas assign it to me @rudrakshi99 
Thank you

**Comment by shivani532** [comment]
Hey, I would like to contribute to this project. Project mentor could you please assign this me
