### ISSUE TITLE
Moving to React on Frontend

### ISSUE THREAD

**Issue by hrushikesh-git** [DSC-JSS-NOIDA/foss-events#111]
As the site is all based on JavaScript wouldn't it be better to move it to the single-page web app using  the famous JavaScript Library React it will become fast responsive [GSSOC'21]

**Comment by PratikGarai** [comment]
I am in favor of this idea and would like to work on this issue too.

**Comment by hritikgupta92** [comment]
I also agree
Modern sites use React for creating front-end components

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
