### ISSUE TITLE
Update the Events 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [DSC-JSS-NOIDA/foss-events#113]
**Describe the bug**
There are events still present whose deadline is already passed I will like to delete all those issues whose end date is passed.

**To Reproduce**
1. See the https://fossevents.netlify.app/ for Eg :- first program which is already over !!

**Expected behavior**

I expect that there should be future events so will not lead to misconception !!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win]
 - Browser [Mozilla Devlopers Edition]
 

**Smartphone (please complete the following information):**

**Additional context**
No for now I think we can just update the sequence and later on will think for improvement !!

**Comment by rohank2502** [comment]
Will start working on it as soon as I get assigned !!

**Comment by servermonk** [comment]
Hey @rohank2502 , I have assigned this issue to you. You can start working on it. All the best

**Comment by rohank2502** [comment]
Thanks @servermonk !! Will get a PR at for it today or at max tomarrow

**Comment by priyakumari02** [comment]
I am GSSOC'21 participant. I want to fix this issue, kindly assign this issue to me.
