### ISSUE TITLE
Add Google Authentication! Firebase

### ISSUE THREAD

**Issue by bhubesh757** [DSC-JSS-NOIDA/foss-events#114]
**Is your feature request related to a problem? Please describe.**
yes
**Describe the solution you'd like**

Hey @deshraj  I Raised a Issue , Lets Have a Authentication to make our Website secure and also from privacy free 
Google , Github , Facebook and Also with linkedin we can Login or Signup using the auth , we can Grab some datas about the users and Also We can REcommend them Which they are interested in
**Describe alternatives you've considered**

**Additional context**

**Comment by Jassi10000** [comment]
Am willing to try some hands on adding Google Authentication , can you assign me under GSSOC'21

**Comment by meghnabajoria** [comment]
@PragatiVerma18 @bhubesh757  I am willing to implement Github Authentication. Can you assign it to me under GSSOC'21?

**Comment by Jassi10000** [comment]
Its been a very long time to this issue , can the maintainers pls assign it that we can contribute
