### ISSUE TITLE
button at nav bar with the name "About Foss Event " 

### ISSUE THREAD

**Issue by barsha119** [DSC-JSS-NOIDA/foss-events#115]
**Is your feature request related to a problem? Please describe.**
Yes, because About page is most important part of any website , I think we should add it.
**Describe the solution you'd like**
We can add button towards the left of the github icon on nav bar which will direct to it's about page.

 I am a participant in GSSOC'21. Please assign me this issue.

**Comment by vanshikapandey** [comment]
Sir I am ready to work on this issue. Please assign this to me

**Comment by 0Faiz0** [comment]
i can do this ,project admin can you assign this issue to me under gssoc21 label

**Comment by simranbhalla3** [comment]
Project admins please assign this issue under gssoc'21 label and assign this issue to me

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by fatma-sia27** [comment]
GSSOC'21
Hello @project admin, please assign this issue to me as I had learned HTML, CSS recently so I can work on this issue.
Thank you.
Aasia fatma
