### ISSUE TITLE
Adding Social media links 

### ISSUE THREAD

**Issue by AviJuneja2007** [DSC-JSS-NOIDA/foss-events#116]
Hey! I am a participant in GSSOC'21. I would like to make this contribution by making a social media sidebar for the site with attractive icons which will hold the links to your social media handles. Please, consider! And assign it to me so that I can start working on it at the earliest.

**Comment by Priyanka7011** [comment]
hii!
I am GSSOC 2021 participant. I would love to work on this . I can make social media panel with few animations which will make it more attractive . I can design it the way you want.

Please Assign me this.
Thank You

**Comment by servermonk** [comment]
Hey @AviJuneja2007, I have assigned this issue to you. You can start working on it. All the best

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by priyakumari02** [comment]
I am GSSOC'21 participant. I want to fix this issue, kindly assign this issue to me.
