### ISSUE TITLE
[GSSoC'21] UI Improvement : Add borders while hovering to the card shaped structure.

### ISSUE THREAD

**Issue by dcs-soni** [DSC-JSS-NOIDA/foss-events#118]
### Add a feature in Website to enhance the UI

**Add Borders while hovering through cards**

While surfing through the web page when the user hovers through the specific type of event ( card ) the card should display some border effects along with its bouncy effect. 

If you think by adding this feature the webpage will look more attractive and if it attracts the user then I would like to work on this issue as a participant of GSSoC'21.

**Comment by yuktagautam** [comment]
Please assign this issue to me under GSSOC'21

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by Shraddha13Jain** [comment]
Please assign this issue to me under GSSOC'21. I would like to contribute to this .

**Comment by Navya-amarneni** [comment]
I found this issue to be interesting.Can you assign this issue to me?

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by Mus2413** [comment]
Hey, I'm gssoc'21 participant, I would like to contribute in this project. I would be thankful if you can assign this issue to me.
