### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by mohammedjameel24** [DSC-JSS-NOIDA/foss-events#121]
add a dynamic favicon for web app

pls assign me this under gssoc212

**Comment by akankshaaa08** [comment]
Can I have this issue assigned to me for contributing under GSSoC'21?

**Comment by SwatiPriya2805** [comment]
I am a GSSoC'21 participant.
I would like to work on this issue. I would be thankful if you can assign this issue to me.

**Comment by sandra9711** [comment]
I'm a GSSOC'21 participant. Kindly assign this issue to me.
