### ISSUE TITLE
Add Dark mode 

### ISSUE THREAD

**Issue by mohammedjameel24** [DSC-JSS-NOIDA/foss-events#122]
dark mode UI

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by oneknucklehead** [comment]
I already have experience in adding a dark mode to websites so I would be grateful if you could assign this issue to me. :)

**Comment by priyamourya** [comment]
I am GSSOC'21 participant and l would like to work on this problem and would add dark mode to website

**Comment by K-jais** [comment]
I can work on this issue efficiently as in the past I have added this feature to my portfolio website.
Link to my portfolio - https://damp-lowlands-00999.herokuapp.com/

**Comment by mohammedjameel24** [comment]
pull request #159

**Comment by Pramit29** [comment]
I am willing to contribute to this issue and add dark mode to the website.

**Comment by 435akashjha** [comment]
if you think the person you have assigned this issue have taken lots of time then you can assign this issue to me I will like to work on this issue and implement dark mode on the website.

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...

**Comment by RakeshCharpe** [comment]
I am beginner in open source contribution I would like to contribute in this project please assign it to me.

**Comment by priyakumari02** [comment]
I would like to resolve this issue please assign me this issue

**Comment by naqeeb2710** [comment]
Hey, Can I work on this issue?
