### ISSUE TITLE
Right Padding 

### ISSUE THREAD

**Issue by mohammedjameel24** [DSC-JSS-NOIDA/foss-events#123]
**Describe the bug**
Right padding is more than left , makes content look ugly and doesn't follow symmetry

**FIx**
mynor changes in CSS

**Comment by vidhi1121** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on this issue...I would be thankful if you can assign this issue to me. I will successfully remove the issue in very little time.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by jaiswalrobin** [comment]
Hey! I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by Ayushgup85** [comment]
is this issue still open?If open i would like to work on this issue
