### ISSUE TITLE
Revamping the webpage with styles to fonts and colors to elements.

### ISSUE THREAD

**Issue by ketakitankk** [DSC-JSS-NOIDA/foss-events#124]
**Describe the bug**
The fonts of the webpage seem pretty plain to me from a user's point of view. The webpage is also lacking some splash of color and a tad of padding in the cards.

**To Reproduce**
1. Go to https://fossevents.netlify.app/
2. Scroll down to the end.
3. See error that is, styles to text and alignment issues too.

**Expected behavior**
I expected that the website would have a dark background with all the white elements floating at just the right place with styles to text and buttons.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oneknucklehead** [comment]
I can look into the issue since I have great hands-on experience in HTML CSS and Javascript. I would like you to assign the issue to me!

**Comment by oneknucklehead** [comment]
GSSoC'21
I can look into the issue and I would like to work on this issue since  I have great hands-on experience in HTML CSS and Javascript. I would be very thankful if you assign the issue to me under GSSoC'21.
