### ISSUE TITLE
issues regarding the cards, footer section and the background.

### ISSUE THREAD

**Issue by oneknucklehead** [DSC-JSS-NOIDA/foss-events#127]
The website looks kind of dull and unattractive. It lacks liveliness such as a background image/color, the footer contents are not aligned properly, and the view cards are also quite dull

**To Reproduce**
1. Go to 'https://fossevents.netlify.app/'
2. The issues mentioned above should be visible

**Expected behavior:**
The Website should have somewhat a dark background or addition of a dark mode to the website seems necessary. Also, the footer contents should be aligned properly with a different color in the footer section. the cards should also be made more attractive.

**Comment by VrindaTyagi** [comment]
Hi! I would like to work on this issue. Kindly assign it to me as a gssoc'21 participant.

**Comment by jaiswalrobin** [comment]
Hey! I would like to work on this issue. Can you assign it to me?

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
