### ISSUE TITLE
[GSSOC'21] Making UI look more attractive like aligning cards to the center and some changes in search bar

### ISSUE THREAD

**Issue by shonali2600** [DSC-JSS-NOIDA/foss-events#128]
Cards are not center-aligned nor attractive. Also, the search bar is looking dull.

Want to fix all the issue related to UI.

**Comment by Fpj-11** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by shonali2600** [comment]
Hey @servermonk, Please assign this issue to me, I would like to work on it as a GSSOC'21 Participant.
