### ISSUE TITLE
Make it responsive for mobile and tablet devices

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#13]
**Describe the bug**
Website becomes mess between medium to x-small devices

**To Reproduce**
1. Go to https://fossevents.netlify.app .
2. Resize screen to 767 px and less
3. See error

**Expected behavior**
1. Cards should be aligned properly and not overflow out of the screen.
2. Footer should not merge with cards.

**Screenshots**
![Screenshot from 2020-09-26 12-20-56](https://user-images.githubusercontent.com/40193621/94332436-fcff9c00-fff2-11ea-9414-52f8f161aa10.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Comment by Manoj13-coder** [comment]
I would Love to work on this issue and make it responsive to mobile phones or laptops .

**Comment by hariom1625** [comment]
Hey, Can I start working on this?

**Comment by PragatiVerma18** [comment]
> Hey, Can I start working on this?

Hi, @hariom1625!!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by hariom1625** [comment]
Sure!! Thanks :-)

**Comment by Abu-Talha-24** [comment]
Hey !  Could you assign this issue to me ! I'd be happy to work on this and leverage my skills

**Comment by PragatiVerma18** [comment]
> Hey ! Could you assign this issue to me ! I'd be happy to work on this and leverage my skills

Hi @Abu-Talha-24 !! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by chinmaikaveti2001** [comment]
Hi! can u pls assign this issue to me...?  I'm  an absolute beginner to open source contribution. can u pls  let me know the way to work on this issue..?

**Comment by naman360** [comment]
https://github.com/DSC-JSS-NOIDA/foss-events/issues/13#issuecomment-699530550

**Comment by abhudaym** [comment]
Hey! Has this issue been resolved? If not, I'd love to work on it!

**Comment by naman360** [comment]
Fixed by #37
