### ISSUE TITLE
[GSSoC'21] Adding a landing page

### ISSUE THREAD

**Issue by shairanshrawat** [DSC-JSS-NOIDA/foss-events#132]
the link which you have provided doesn't have a landing page it directly started from the event 
I would be making a landing page so as to make it more attractive to the use. It will include the following

- creating a navbar
- designing the front page 
- telling about the website and how can it help 
- user can then click on the navbar for more event details 
- and creating the footer 

I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021?
Thank you

**Comment by Navya-amarneni** [comment]
I found this issue to be interesting.Can you assign this issue to me?

**Comment by AishwaryaArun15** [comment]
Hello,
I am interested to work on this issue.
Please assign

**Comment by jaiswalrobin** [comment]
Hey, I want to work on this issue. please assign it to me.

**Comment by Shraddha13Jain** [comment]
/assign
Hey!! @shairanshrawat  , I am a participant of GSSoC'21. I would take up this issue.
Can you please assign me this issue.

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
