### ISSUE TITLE
I would like to add more open source programmes.

### ISSUE THREAD

**Issue by nabin-nath** [DSC-JSS-NOIDA/foss-events#135]
I would like to add more open source programmes like
1. Season of Docs
2. Season of KDE
3. OWASP SOC
4. Mozilla Winter of Security
5. RGSOC
6. Tweag I/O Summer Internship
7. TOR Summer of Privacy
8. SOCIS
9. Linux Foundation Networking Internships
10. The X.Org Endless Vacation of Code (EVoC)
11. DataONE Summer Internship Programme
12. Julia Summer of Code
13. OWASP Code Sprint
14. Free Software Foundation Internship
15. Radare Summer of Code
16. Summer of Haskell
17. Open Mainframe Project - Linux Foundation 
18. Processing Foundation Fellowship 
19. Segment Open Fellowship 
20. RARE Technologies Student Incubator Programme 
21. Open Summer of Code 
22. FOSSASIA Internship Programme 
23. Hyperledger Internship Program 
24. Snowplow   
25. ICFOSS 
26. ERPNext Summer of Code 
27. Redox Summer Of Code
28. Millennium Fellowship
29. John Hunter Matplotlib Summer Fellowship 
30. GNOME Internship Program
31. Igalia Coding Experience Program
32. Google Summer of Earth Engine
33. Alibaba Summer of Code
34. ICFOSS Fellowship Programme
35. Linux Kernel Mentorship Program
36. Community Bridge Mentorship (by Linux Foundation)

**Comment by servermonk** [comment]
Hey @nabin-nath , I have assigned this issue to yo. You can start working on it

**Comment by nabin-nath** [comment]
Thankyou

**Comment by Kritika495** [comment]
can I work on this issue

**Comment by PSoni8** [comment]
I am Participant of GSSOC'21. Can I also work on same?

**Comment by PragatiVerma18** [comment]
Hey @nabin-nath, do you have any updates on this. If you have made any PR, please link it to this issue for easy approval.

**Comment by K-jais** [comment]
I have added 11 more events. Please look into it PR #176 .
