### ISSUE TITLE
Adding Registration date information on event cards.

### ISSUE THREAD

**Issue by shalmoly79** [DSC-JSS-NOIDA/foss-events#136]
**Is your feature request related to a problem? Please describe.**
I am a GSSOC'21 participant. Event starting and ending date is given. If registration start and end dates are added, it would be much helpful.

**Describe the solution you'd like**
I want to add Registrations open and close date on the event cards.

**Comment by servermonk** [comment]
hey @shalmoly79 , I have assigned this issue to you. You can start working on it

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by priyakumari02** [comment]
I am GSSOC'21 participant. I want to fix this issue, kindly assign this issue to me.

**Comment by PragatiVerma18** [comment]
@shalmoly79 please link your PR to this issue if you have made one, or else it will be re-assigned to some other participant.

**Comment by raks924** [comment]
I am GSSOC'21 participant. Kindly assign this issue to me. I would love to work on this as my first PR

**Comment by ShrutiKhatri826** [comment]
I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.
