### ISSUE TITLE
Add Contribution section in read me which will get updated automatically 

### ISSUE THREAD

**Issue by rohank2502** [DSC-JSS-NOIDA/foss-events#137]
I will like to update readme file in which I will like to add the contribution section which will keep updating ! Will start working on the issue as soon as I get assigned !!

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC21. Can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @rohank2502, can you elaborate on what are you planning to do for this? Will you be using something like `sourcerer.io` or or `all-contributors` bot or use Git Hooks to implement this?

**Comment by rohank2502** [comment]
> 
> 
> Hey @rohank2502, can you elaborate on what are you planning to do for this? Will you be using something like `sourcerer.io` or or `all-contributors` bot or use Git Hooks to implement this?

Yes sure I am planning to use the all contributor img tag this look great and don't take much space in read me
