### ISSUE TITLE
Transition on hovering card

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#14]
**Describe the bug**
Card scales to smaller size when hovered with a transition , and when cursor is removed from the card it scales back to its original size without a transition which kinda looks odd.

**To Reproduce**
1. Go to ' https://fossevents.netlify.app/ '
2. Hover on any card.
3. See error

**Expected behavior**
Same transition should appear when hovering and removing hover from the card.

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Comment by gokulkannan7** [comment]
sir, I would love to work on this issue, can u assign it to me?

**Comment by naman360** [comment]
Hi, @gokulkannan7 !!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020. See you then! Keep Learning :octocat:

**Comment by gokulkannan7** [comment]
Yaa sure sir, thank you!!

**Comment by skamp91** [comment]
Hey :) Can I also work on this? or isn't is possible?
GoodRegards

**Comment by naman360** [comment]
https://github.com/DSC-JSS-NOIDA/foss-events/issues/14#issuecomment-699589031

**Comment by ventodeco** [comment]
so we can contribute it and make pr, without assign it to us sir?

**Comment by PragatiVerma18** [comment]
> so we can contribute it and make pr, without assign it to us sir?

@ventodeco contribute and make a PR only when we have assigned the issue to you.  We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020, till then Star and Fork this repo. See you then! Keep Learning :octocat:

**Comment by naman360** [comment]
@gokulkannan7 update?

**Comment by me-harshit** [comment]
Hey! If this issue hasn't been resolved, I'd like to work on it!   : )

**Comment by naman360** [comment]
@me-harshit Go ahead

**Comment by naman360** [comment]
Fixed.
