### ISSUE TITLE
Adding animations to the landing page

### ISSUE THREAD

**Issue by AishwaryaArun15** [DSC-JSS-NOIDA/foss-events#140]
I would like to add some animations to the Landing page.
It makes the page more attractive and interactive.
Please assign me to this issue.

**Comment by Tanu-priya-Roy** [comment]
> Thanks for opening this issue, a maintainer will get back to you shortly!

I would like to work on this issue. Please assign it to me.

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.

**Comment by AkshaySharma008** [comment]
@Tanu-priya-Roy @Avnish5  Please explain your flow of thought briefly with technical solution, so that I could assign this issue to either of you.

**Comment by Tanu-priya-Roy** [comment]
I want to add some animation with the help of CSS in the front end part. It
would make the web page more attractive.

**Comment by Avnish5** [comment]
Sir just wait i am sending you my technical solution in the wireframe

**Comment by Avnish5** [comment]
@AkshaySharma008 Sir i am going to use the HTML5,CSS3,BOOTSTRAP AND JAVASCRIPT to create the landing page.

This landing page have navbar at the top through which user can navigate to different pages of our website.

In the landing page we will adding the some events of open source which are happen around the globe.

We can add some more info in the landing page about how this website is gonna help them about stay update about the open source  events around the globe.

In the landing page we are going to telling about the different features of the  website.I mean what type of functionality or info we are going to serve to the user.

**Comment by AishwaryaArun15** [comment]
@AkshaySharma008 sir, I think this issue concentrates on how interactive the landing page can be.
For example,
Animations when when we first open the landing page .(css, bootstrap)
Adding hover/click effects to the buttons or sections on the landing page.(css)
Adding labels or carousels using (bootstrap).
We can alert the users with [toasts ](https://www.w3schools.com/bootstrap4/bootstrap_toast.asp)( bootstrap). 
Please assign this issue to me. I'd love to contribute to this issue.

**Comment by AkshaySharma008** [comment]
Yes, @AishwaryaArun15, you are right, I would like you to proceed further and @Avnish5 you can connect with @AishwaryaArun15 and altogether solve this, by this manner you will also learn how to work in collaboration.
Assigning this issue to @AishwaryaArun15.

**Comment by AishwaryaArun15** [comment]
Thankyou so much @AkshaySharma008 , will give my best.

**Comment by Avnish5** [comment]
> Yes, @AishwaryaArun15, you are right, I would like you to proceed further and @Avnish5 you can connect with @AishwaryaArun15 and altogether solve this, by this manner you will also learn how to work in collaboration.
> Assigning this issue to @AishwaryaArun15.

okk sir thank you
