### ISSUE TITLE
Adding filter feature to the search bar(gssoc 21)

### ISSUE THREAD

**Issue by kaffan** [DSC-JSS-NOIDA/foss-events#141]
i want to add the filtering feature to the search bar on the front page

**Comment by abhishek96k** [comment]
Hii @PragatiVerma18 
I am Abhishek and I am participating for GSSOC'21 .So I would like to contribute to this project.
So kindly do `/assign` me this task.

**Comment by jaiswalrobin** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @kaffan, go ahead and give it a try, assigning it to you. Reach out in case of any doubts.
