### ISSUE TITLE
Website is not showing event

### ISSUE THREAD

**Issue by flyingsonu122** [DSC-JSS-NOIDA/foss-events#143]
**Describe the bug**
Website is not working due to syntax error in events.json file

![IMG_20210313_190253](https://user-images.githubusercontent.com/51280276/111031754-196f8380-842f-11eb-8740-817543f0b658.jpg)

Comma is missing after the events

**Comment by aniketlodh** [comment]
I have made a PR that addressed this syntax error.

**Comment by flyingsonu122** [comment]
Alright @aniketlodh go ahead
