### ISSUE TITLE
Would like to make the website responsive

### ISSUE THREAD

**Issue by Tanu-priya-Roy** [DSC-JSS-NOIDA/foss-events#145]
Responsive Website is a necessary part. I would like to work on the responsiveness of the Website so that it is user friendly and interactive, as a part of GSSOC'21.

**Comment by Tanu-priya-Roy** [comment]
Yes I would like to make the website responsive. Please assign it to me.

**Comment by jaiswalrobin** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by Ananya-Sharma** [comment]
I would like to contribute to this issue. Can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @Tanu-priya-Roy, you can go ahead and start working on this issue, assigning it to you.

**Comment by Tanu-priya-Roy** [comment]
Thank u so much mam

**Comment by Muskan-creator** [comment]
I would like to make website responsible as a part of GSSOc'21 contributor.Please assign this issue to me

**Comment by Tanu-priya-Roy** [comment]
It's already assigned to me.

**Comment by Amit366** [comment]
@PragatiVerma18 can I work on this issue??

**Comment by Tanu-priya-Roy** [comment]
I have already been assigned this issue. Please work on an issue that is
not assigned to anyone. See thv tags first.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Tanu-priya-Roy** [comment]
I have been assigned this issue alreday and I am working on that issue so
please u can search for another issue.

**Comment by Tanu-priya-Roy** [comment]
Made the website responsive.
