### ISSUE TITLE
Adding a small introductory video about the events

### ISSUE THREAD

**Issue by Tanu-priya-Roy** [DSC-JSS-NOIDA/foss-events#146]
As a new viewer will see the website they will at first try to know what it is about and adding a video will act like a boon . I would like to add the Video feature or link at the starting of the web page as a part of GSSOC'21. please assign me this issue as this will make the web page attractive.

**Comment by vidhi1121** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @Tanu-priya-Roy, this won't be possible for each and every event. This can't be done manually for each event. Please find some other issue to work on, closing this one.
