### ISSUE TITLE
Implement Pagination.

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#15]
**Is your feature request related to a problem? Please describe.**
Contributors will add events card which will lead to many cards on a single page which is less manageable. 

**Describe the solution you'd like**
Implement pagination with 10-12 cards on a page.

**Comment by chinmaikaveti2001** [comment]
hi!  sir.. can u pls assign  this  issue to me..?
I want to work on this issue....

**Comment by gitaalekhyapaul** [comment]
@naman360 I would like to work on the backend for pagination

**Comment by naman360** [comment]
@gitaalekhyapaul there is no need to work on backend for pagination.

**Comment by naman360** [comment]
@chinmaikaveti2001 status?

**Comment by chinmaikaveti2001** [comment]
working on it ....@naman360

**Comment by naman360** [comment]
@chinmaikaveti2001 status?
