### ISSUE TITLE
update events.json file by adding information about processing foundation fellowship program

### ISSUE THREAD

**Issue by hritikgupta92** [DSC-JSS-NOIDA/foss-events#150]
I'll be adding information processing foundation fellowship program i.e its timeline, organisation and link to its website

**Comment by hritikgupta92** [comment]
@sehgalayush1 please assign this issue to me

**Comment by hritikgupta92** [comment]
@deshraj @spyshiv @sehgalayush1 @singhsterabhi please assign this issue to me

**Comment by PragatiVerma18** [comment]
Hey @hritikgupta92, please do not tag people other than the assigned mentors for the GirlScript Summer Of Code. DSC JSS is an organization and not everyone is involved with this project, so do not tag anyone who may not be concerned.

Talking of the issue, you can go on and add the event info, assigning this issue to you.

**Comment by hritikgupta92** [comment]
> Hey @hritikgupta92, please do not tag people other than the assigned mentors for the GirlScript Summer Of Code. DSC JSS is an organization and not everyone is involved with this project, so do not tag anyone who may not be concerned.
> 
> Talking of the issue, you can go on and add the event info, assigning this issue to you.

Sorry,I'll take care from next time

**Comment by hritikgupta92** [comment]
@PragatiVerma18  can you check #186
