### ISSUE TITLE
We can also add upcoming event flashing notice board 

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [DSC-JSS-NOIDA/foss-events#152]
**Is your feature request related to a problem? Please describe.**
can directly redirect to the upcoming specific event

**Describe the solution you'd like**
we can add upcoming event flashing notice board.

**Additional context**
the upcoming notice board should be only updated by the Admin or authorized one.

Can you please assign it to me .....

**Comment by PragatiVerma18** [comment]
Hey @ASHISH-GITHUB2495, can you describe a bit more? Are you talking about the flashing notices as on e-commerce or government websites? Attach some screenshot to explain better, will assign you if the feature seems required.

**Comment by ASHISH-GITHUB2495** [comment]
Like this we can add Upcoming Event board ...

![Capture](https://user-images.githubusercontent.com/57385079/111735883-c53b2800-88a2-11eb-994e-36765c3b6318.JPG)
