### ISSUE TITLE
we can add "Get in touch section" of "feedback section" in the footer of the website.

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [DSC-JSS-NOIDA/foss-events#153]
**Is your feature request related to a problem? Please describe.**
we can add "Get in touch section" of "feedback section" in the footer of the website.

**Describe the solution you'd like**

![Screenshot (15)](https://user-images.githubusercontent.com/57385079/111073352-5bb6c480-8504-11eb-8e1c-67f72617a368.png)

### I have already coded the "Get in touch section" if this issue is good i can also code feedback section
also I can attach database to it.

_If you think this is good issue can you please assign it to me._

**Comment by vidhi1121** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @ASHISH-GITHUB2495, can you make some changes to the UI and maybe share mockups because the screenshot doesn't align with the UI of the project, might end up looking inconsistent. Feedback section can be a cool feature, can you share more details as in what are you planning to put in there.

**Comment by ASHISH-GITHUB2495** [comment]
**Actually , mam I want to add some feature to the footer section, where any one can write feedback or want to contact or suggest feature etc.. or even he/she wants to give some information regarding any event.**

### And those above screenshot is actually just an idea ... i will write code with new UI which will compatible to the website..

**Comment by ANSHIKA1806** [comment]
@PragatiVerma18 @ruchikamuddinagiri @rudrakshi99 @AkshaySharma008 
Please assign this task to me , I am good in this task , I had done this type of task earlier . I would to contribute in this project.
Get in touch section is very important part of any website ,it helps user to connect more .
![getintouch](https://user-images.githubusercontent.com/71966377/111902668-92d92880-8a64-11eb-82f3-c3bbe9d2c412.png)
