### ISSUE TITLE
Dropdown events in Search input tag

### ISSUE THREAD

**Issue by K-jais** [DSC-JSS-NOIDA/foss-events#154]
Dropdown the events which have been there in the events.json and also having that search thing in the input text tag like the datalist tag with options tag as the events in the events.json.

**Comment by PragatiVerma18** [comment]
Hey @K-jais, go ahead, assigning the issue to you. Reach out in case of any doubts.

**Comment by K-jais** [comment]
Thank you for assigning me this issue.

**Comment by AkshaySharma008** [comment]
Amazing work @K-jais, closing this issue now.
