### ISSUE TITLE
Filters to find the event , one is interested in. 

### ISSUE THREAD

**Issue by RubenFalcao14** [DSC-JSS-NOIDA/foss-events#156]
The site does not have a filter option , which tends to waste one's time in finding the event which one likes.
I would like to add filter option to the site to make it easy for a person to find the event of his choice faster.
I'm a GSSOC'21 participant, I would love to include the filter in the site.
Thank You.

**Comment by Pramit29** [comment]
I can try working on this issue although I am a beginner and just started to contribute.

**Comment by 435akashjha** [comment]
I want to work on this issue can you assign this to me

**Comment by sanjanasingh31** [comment]
Hello ,I am a gssoc'21 participant and would like to work on this issue
