### ISSUE TITLE
Adding CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by rajeshpanjiyar** [DSC-JSS-NOIDA/foss-events#157]
**Hi,** I would like to add a contributors file to add the **name and GitHub handle** of respected contributors.
- I am a participant under GSSoC'21

**Comment by lakshita15** [comment]
hi , i'm gssoc'21 participant
I want to work on this issue
Can you assign issue to me ?
i'll submit before deadline

**Comment by PragatiVerma18** [comment]
Hey @rajeshpanjiyar, please specify if you're talking of a webpage using HTML in the website or do you just intend to add a `contributors.md` file and add names to it. The latter won't be a good idea for me.

**Comment by rajeshpanjiyar** [comment]
Contributors section in readme file would be better
