### ISSUE TITLE
Search/Filter feature

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#16]
**Is your feature request related to a problem? Please describe.**
Website will contain many events , so it would be difficult to find a particular event.

**Describe the solution you'd like**
Implement a search/filter feature on the basis of name of the event.

**Comment by Manoj13-coder** [comment]
I like to contribute in it but please can you tell me from where i get the list of names of events?

**Comment by naman360** [comment]
Hey @Manoj13-coder !! We are glad that you want to contribute to this project , but we would advise you to start contributing from 1st October to make it count under Hacktoberfest 2020. Till then fork :fork_and_knife:  and star :star2:  this repository. :octocat:

**Comment by Manoj13-coder** [comment]
yes of course but can you tell me about list of events ?

**Comment by naman360** [comment]
Contributors need to add event on there own.

**Comment by Manoj13-coder** [comment]
ok

**Comment by mohitn787** [comment]
Hey @naman360 I would love to contribute to your project can just elaborate about the features that you are looking for.

**Comment by Manoj13-coder** [comment]
i will PR it on october 1st

**Comment by Manoj13-coder** [comment]
i have to make changes in foss-events/Frontend/data/events.json ?

**Comment by paarth17032000** [comment]
Hi @naman360 I would like to help you with the issue

**Comment by naman360** [comment]
@paarth17032000 If @Manoj13-coder is unable to do it then you can go on with it.

**Comment by naman360** [comment]
@Manoj13-coder You simply need to implement search feature on events that are added from events.json

**Comment by paarth17032000** [comment]
@naman360 I have made a PR regarding the issue, please review it.

**Comment by naman360** [comment]
@Manoj13-coder you still working on it, @paarth17032000 has made a valid working PR which looks good to me and I am merging it.

**Comment by Manoj13-coder** [comment]
ok merge it sorry for my delay

**Comment by aadij6401** [comment]
@servermonk Is the issue still open?
If yes then I would love to contribute.

**Comment by naman360** [comment]
Fixed by #41
