### ISSUE TITLE
Contact Us, Social Media Footer Section

### ISSUE THREAD

**Issue by K-jais** [DSC-JSS-NOIDA/foss-events#161]
We can add the contact us and social media connectivity to this website. In that portion, we can add a form if anyone has any query they can ask there and if he submits the form then we will get back his query in form of mail. And in that section, we can add social media icons for its connectivity.

**Comment by Subhangini** [comment]
I would like to work on this issue as a gssoc participant

**Comment by samidha28** [comment]
I would be happy to work on this .please assign this issue to me

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.

**Comment by PragatiVerma18** [comment]
@K-jais since you made the issue, assigning it to you. Reach out in case of any doubts.

**Comment by K-jais** [comment]
Thank you for assigning me this issue.

**Comment by K-jais** [comment]
Thank you for assigning me this issue.

**Comment by K-jais** [comment]
Review this pull request as I have added the contact us and the social media icons in the footer section.

**Comment by K-jais** [comment]
> Review this pull request as I have added the contact us and the social media icons in the footer section.

PR #194

**Comment by K-jais** [comment]
> Review this pull request as I have added the contact us and the social media icons in the footer section.

PR #201

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue? i have experience in css,js
