### ISSUE TITLE
Changing the appearance of the cards and adding more themes and font styles to the website

### ISSUE THREAD

**Issue by guruc-134** [DSC-JSS-NOIDA/foss-events#166]
**Is your feature request related to a problem? Please describe.**
This feature is related to the UI/ appearance of the website
**Describe the solution you'd like**

I would like to change the appearance of the cards, add some shadows, change some animations. 
I would also like to add a feature that would let the user change the themes and font styles of the website, cause I think customizability is very important to attract more users to use the website and also give them a sense of control over the website

**Comment by guruc-134** [comment]
thanks for assigning this issue to me

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.

**Comment by kavita1403** [comment]
I'm very much interested to work on it. I would like to work on it.
I can change the appearance of the cards by adding CSS.
We can make the website user friendly by providing different options to users to change the theme and font styles.
Please assign this to me.
Thankyou!
