### ISSUE TITLE
Differentiating between active events and closed events

### ISSUE THREAD

**Issue by pinnacle20** [DSC-JSS-NOIDA/foss-events#167]
I would like to change border color of open source events which are ended now so that user gets to know about active events to participate.
It will increase good user experience .

Shivanand, GSSOC'21 participant.
Thank you

Before
![before](https://user-images.githubusercontent.com/73813570/111383799-bdc32580-86ce-11eb-923a-0d8c5a73d7a3.jpg)

After
![after](https://user-images.githubusercontent.com/73813570/111383810-c156ac80-86ce-11eb-8af0-c1e3b278ba6f.jpg)

**Comment by PragatiVerma18** [comment]
Hey @pinnacle20, sounds good. Go ahead and give it a try, assigning this issue to you.
