### ISSUE TITLE
Implement Update Route

### ISSUE THREAD

**Issue by servermonk** [DSC-JSS-NOIDA/foss-events#17]
**Is your feature request related to a problem? Please describe.**
Contributors will add update route for the event

**Describe the solution you'd like**
The route will be as follows;
 - Path- "/event/:title"
 - Method- Update
 - Details- Users will be able to update a particular Event title, Event Date, Website and other details using this route
> Note: This will be an authorized route

**Comment by Sudhee-bsp** [comment]
I would like to work on it. Please add me as an Assignee :) @PragatiVerma18

**Comment by servermonk** [comment]
hey @Sudhee-bsp I have assigned this issue to you. All the best!!

**Comment by aadij6401** [comment]
I want to work on it Plz assign to me @PragatiVerma18 @diyajaiswal11 @servermonk

**Comment by aadij6401** [comment]
please reply guys I am eagerly waiting for contribution...

**Comment by aadij6401** [comment]
Please add me as assignee!

**Comment by servermonk** [comment]
hey @atishaya11 sorry for the late reply. We are glad to hear that you want to contribute to this project but unfortunately this issue has already been assigned to @Sudhee-bsp . If he decides not to work on it then we will assign it to you. Meanwhile you could check other issues also we would add few more issues soon.

**Comment by servermonk** [comment]
hey @aadij6401 , sorry for the late reply. We are glad that you want to contribute to our project but unfortunately this task is already assigned to @Sudhee-bsp , if he decides to not work on it then we will assign this issue to you. Meanwhile you could check out other issues, also we would adding more issues .

**Comment by Sudhee-bsp** [comment]
hey @servermonk , I have made PR adding the Event Update endpoint, and also reference screenshots. Please let me know any furthur changes. Thanks :)
