### ISSUE TITLE
Introduce a filter that could filter events between specified dates

### ISSUE THREAD

**Issue by tend2infinity** [DSC-JSS-NOIDA/foss-events#170]
**Introduction**
Hii, I am a Gssoc participant and I would like to work diligently upon the issue explained below, please assign that to me.
**Description of the problem**
What if a student wants to search for open source events in a particular time frame, maybe he/she is free only for that particular time frame.

**Solution**
I can create a filter in which the user can specify the start date and end date in which the user is vacant and based on that we can get the organizations that host events in that particular interval.

**Approach**
I have access to the start and end date of an event, so I can make use of that and compare the user entered dates with the dates for all the organizations to get the desired results. For comparison of dates, I would use the ISO format.

**Additional context**
I will create an additional field below the search bar in which the user can enter the required dates.

**Comment by PragatiVerma18** [comment]
Hey @tend2infinity, that would be a great addition to the project, go ahead and give it a try. Reach out in case of any doubts, assigning this issue to you.

**Comment by tend2infinity** [comment]
@PragatiVerma18 I need to convert the start and end dates in dd/mm/yyyy format before I could compare them, can I do that in the events.json file?
