### ISSUE TITLE
Removing 24 PULL REQUESTS  card

### ISSUE THREAD

**Issue by satcasm** [DSC-JSS-NOIDA/foss-events#174]
24 PULL REQUESTS seems to be taking this year off. So , I think that card is unnecessary as of now.
Would like to remove that card as a part of GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/111599400-396bc200-87f6-11eb-9e77-cd33fdb72415.png)

**Comment by PragatiVerma18** [comment]
Hey @satcasm, you can go ahead and remove this card, assigning this issue to you.
