### ISSUE TITLE
Creating About page

### ISSUE THREAD

**Issue by fatma-sia27** [DSC-JSS-NOIDA/foss-events#175]
Hey, I think if we will make a about page after that dark amd light mode button then it would increase beautify of this website. I really wanted to create a "about" page so please aasign me this issue.
Thank you

**Comment by PragatiVerma18** [comment]
Hey @fatma-sia27, you can go ahead and make an about page, remember to drop a demo video/screenshots once you've finished. I am assigning this issue to you. Reach out in case of any doubts.

**Comment by fatma-sia27** [comment]
> Hey @fatma-sia27, you can go ahead and make an about page, remember to drop a demo video/screenshots once you've finished. I am assigning this issue to you. Reach out in case of any doubts.

Thank you maam for assigning this issue to me. I will try to make about page as awesome as I can.

**Comment by fatma-sia27** [comment]
> Hey @fatma-sia27, you can go ahead and make an about page, remember to drop a demo video/screenshots once you've finished. I am assigning this issue to you. Reach out in case of any doubts.

Maam should I send a pull request for this??

**Comment by parthpandyappp** [comment]
@PragatiVerma18 Do let me know if @fatma-sia27 's PR doesn't satisfy the need. I'm also a GSSoC participant and would like to get this issue assigned to me in such a case.

**Comment by rudrakshi99** [comment]
> > Hey @fatma-sia27, you can go ahead and make an about page, remember to drop a demo video/screenshots once you've finished. I am assigning this issue to you. Reach out in case of any doubts.
> 
> Maam should I send a pull request for this??

Yes, open a pull request and add a demo video/screenshots in its description. Also, make sure you will link your pull request to the issue.

**Comment by fatma-sia27** [comment]
@rudrakshi99  @PragatiVerma18  Maam since Iam making about page so it require some information about "FOSS EVENT" . So will you provide me this information or I should code it in the form of lorem ipsum ??
Thank you

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by rudrakshi99** [comment]
@fatma-sia27 **FOSS**  is basically **Free and Open Source Software**. There are lots of information available on the internet. If you want to know about this in-depth then do refer to [this](https://itsfoss.com/what-is-foss/) or else try to search about it.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 **FOSS** is basically **Free and Open Source Software**. There are lots of information available on the internet. If you want to know about this in-depth then do refer to [this](https://itsfoss.com/what-is-foss/) or else try to search about it. Here, FOSS Events is a website that provides information about world-wide events related to FOSS.

Ook thank you , I will do that.

**Comment by ambivert-sam** [comment]
Hi, I am a GSoC participant, can I work on this issue?

**Comment by mansijain980** [comment]
@PragatiVerma18 Please assign this to me.
