### ISSUE TITLE
Sticky/Fixed Navbar

### ISSUE THREAD

**Issue by Saatvik21** [DSC-JSS-NOIDA/foss-events#177]
**Is your feature request related to a problem? Please describe.**
- Currently, the navbar isn't fixed/sticky on scrolling down.

**Describe the solution you'd like**
- As a participant of GSSoC'21, I would like to make navbar fixed/sticky.

**Describe alternatives you've considered**
- `NA`

**Comment by PragatiVerma18** [comment]
Hey @Saatvik21, you can go ahead and make the changes, remember to drop a demo video once you've finished. I am assigning this issue to you. Reach out in case of any doubts.
