### ISSUE TITLE
Adding the shadow feature for the card

### ISSUE THREAD

**Issue by ishuu7** [DSC-JSS-NOIDA/foss-events#179]
**Is your feature request related to a problem? Please describe.**
We can add the box shadow feature for the events card, so it looks more pretty.

**Describe the solution you'd like**
Initially all the cards events will have some shadow, on hovering as the card moves back, shadow also reduces. I can do this using box-shadow with hover property of css.

**Additional context**
I am a GSSOC 2021 participant and creating the first issue please assign this issue to me.

**Comment by PragatiVerma18** [comment]
Hey @ishuu7! Sounds good, you can go ahead and give it a try, I am assigning this issue to you.

**Comment by ishuu7** [comment]
Hey @PragatiVerma18 ! I have made a PR, can you please check it, Thanks.

**Comment by rudrakshi99** [comment]
> Hey @PragatiVerma18 ! I have made a PR, can you please check it, Thanks.

Link your PR with the issue.
