### ISSUE TITLE
Implement Delete Route

### ISSUE THREAD

**Issue by servermonk** [DSC-JSS-NOIDA/foss-events#18]
**Is your feature request related to a problem? Please describe.**
Contributors will add a delete route for the event

**Describe the solution you'd like**
The route will be as follows;
 - Path- "/event/:title"
 - Method- Delete
 - Details- Users will be able to delete a particular event using this route
> Note: This will be an authorized route

**Comment by rishavjaiss** [comment]
Hi, I can take this up if you can share with me the file in which the change needs to be done or, the route is to set up from scratch?. I can't see any existing backend files in this repo.

**Comment by servermonk** [comment]
Hi, @rishavjaiss  !!! We're glad that you want to contribute to this project but we would advise that start contributing from 1st October so as to make it count under Hacktoberfest 2020, till then Star and Fork this repo. See you then! Keep Learning..
Also FYI, all the backend-related files are in [backend](https://github.com/DSC-JSS-NOIDA/foss-events/tree/backend) branch. So, you might want to check that out before contributing!!!

**Comment by rishavjaiss** [comment]
Gotcha. Yes, I'll making pr in the month of October if you assign this to me.

**Comment by servermonk** [comment]
hey @rishavjaiss I have assigned this task to you, so you could start working on it. All the best!!
