### ISSUE TITLE
To make the entire div clickable

### ISSUE THREAD

**Issue by Sreelayavuyyuru** [DSC-JSS-NOIDA/foss-events#181]
Having the entire div clickable will make it easy for the users, they don't have to click on the "More info" every time they want to open a page.

Make the entire div clickable so that they can click anywhere inside the box to open the page.

I would like to try implementing this.

**Comment by Sreelayavuyyuru** [comment]
@PragatiVerma18 Kindly assign this to me.

**Comment by ruchikamuddinagiri** [comment]
Are you a GSSOC'21 participant?

**Comment by Sreelayavuyyuru** [comment]
Yes, I am
