### ISSUE TITLE
desgin scrollbar

### ISSUE THREAD

**Issue by Goheljay** [DSC-JSS-NOIDA/foss-events#185]
My name is Jay Gohel. I am a Gssoc Participant.

**Is your feature request related to a problem? Please describe.**
I can design or customize and some changes to the scrollbar.
**Describe the solution you'd like**
I design or customize scrollbar size and color in both dark mode and white mode.

**Additional context**
I would like to try implementing this. So can you assign me?

**Comment by rudrakshi99** [comment]
@Goheljay You can go ahead. :+1:

**Comment by Goheljay** [comment]
thank you

**Comment by Goheljay** [comment]
https://github.com/DSC-JSS-NOIDA/foss-events/pull/196 I have successfully sent PR. Please check it out
