### ISSUE TITLE
To change text in the search bar

### ISSUE THREAD

**Issue by DhairyaDutt** [DSC-JSS-NOIDA/foss-events#187]
**Describe the bug**
The text in the search bar is not grammatically perfect.

**Expected behavior**
The text "Search for an event here....." is more appropriate and correct.

so kindly assign it to me if it's worth changing. peace out.

**Comment by ANSHIKA1806** [comment]
@PragatiVerma18 @rudrakshi99 @AkshaySharma008 @ruchikamuddinagiri 
Please assing this task to me , I am good in this task , I had done this type of task earlier . I would love to contribute in this project.

**Comment by DhairyaDutt** [comment]
@PragatiVerma18 @rudrakshi99 i have already made the changes, plz assign this issue to me

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by rudrakshi99** [comment]
> @rudrakshi99 I've made the changes and sent a PR, plz check it out.
> Peace out.

Where you have resolved the merge conflicts? I am not able to find it in your linked PR.

**Comment by ANSHIKA1806** [comment]
@rudrakshi99 Please assign this issue to me. I am good at this type of tasks.
