### ISSUE TITLE
Problem in README.md

### ISSUE THREAD

**Issue by sonalsingh25** [DSC-JSS-NOIDA/foss-events#188]
**Describe the bug**
In the README.md "A simple website **with** a collection of open-source" can be changed to "A simple website **which has a** collection of open-source" and also instead of " learn git and contribute to **web projects** ." I guess it should be " learn git and contribute to **various** projects."
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Hello. I'm a gssoc participant if you find the above correction fit then please assign them to me.

**Comment by ANSHIKA1806** [comment]
@PragatiVerma18 
Hello mam, please assign this task to  me , I am good in this . I would love to contribute in this project.

**Comment by sonal251001** [comment]
Hey @PragatiVerma18 I opened the issue first if the change is required then please assign it to me.
