### ISSUE TITLE
Set Expiraiton time of JWT token

### ISSUE THREAD

**Issue by servermonk** [DSC-JSS-NOIDA/foss-events#19]
**Describe the bug**
Set expiration time of JWT token to 15mins

**To Reproduce**
In Postman: 
1. Generate JWT token by going to the path - "/users/login"
2. Notice that the generated JWT token never expires

**Expected behavior**
Set the expiration time of JWT token to 15 mins. After 15 mins, the token should expire and the user should not be able to access the protected routes

**Comment by MukulTan10** [comment]
hey, i am very new to this language , and open source as well, i would love to see this issue and figure if i can solve it ot not, can i do that ? and can you help me a little more in understanding same?

**Comment by servermonk** [comment]
Hey @MukulTan10  !! We are glad that you want to contribute to this project , but we would advise you to start contributing from 1st October to make it count under Hacktoberfest 2020. Till then fork 🍴 and star 🌟 this repository.
Check out the  readme of this Repo if you have any doubts related to Backend Structure and Code

**Comment by hariom1625** [comment]
Hey @servermonk, I understood your concern I would like to work on this issue.

**Comment by servermonk** [comment]
Sure @hariom1625, All the Best and Happy Hacktober!!
