### ISSUE TITLE
Scroll to Top button on the home page

### ISSUE THREAD

**Issue by DEEPALI-SUK** [DSC-JSS-NOIDA/foss-events#190]
**Is your feature request related to a problem? Please describe.**
Yes, Scroll to Top button is not present on home page and content is also more on the home page, so for user convenience scroll to top button should be present.

**Describe the solution you'd like**
I would like to add this as a new feature for the website.

Kindly assign me this issue as a part of GSSOC 2021.

**Comment by DEEPALI-SUK** [comment]
@PragatiVerma18 @rudrakshi99 Kindly assign me this issue as a part of GSSOC 2021.

**Comment by rudrakshi99** [comment]
@DEEPALI-SUK Go ahead.

**Comment by DEEPALI-SUK** [comment]
@rudrakshi99 Kindly review my PR.

**Comment by Goheljay** [comment]
@rudrakshi99 I have code for scrollbar and PR it. But right now not display my PR and also not listed my profile in contributor list. why? 
Please Give me an answer?
My PR is considered or not in gssoc?

my PR is https://github.com/DSC-JSS-NOIDA/foss-events/pull/196
