### ISSUE TITLE
`Propose new program` fetaure to add new open-source events to the collection.

### ISSUE THREAD

**Issue by parthpandyappp** [DSC-JSS-NOIDA/foss-events#191]
**Is your feature request related to a problem? Please describe.**
It's not related to any problem/issue! It's just an enhancement that will bring something lucrative to this project.

**Describe the solution you'd like**
Actually, this is a proposal to the idea for adding a feature `Propose new program` or `Add more programs`, where a user will be able to propose new programs to this web portal making it worth surfing. Initially, the user will be provided with a simple form with relevant fields to propose and request any new program to be added to the portal/website. After the user submits the form, an issue will be opened up at the GitHub repository of the project where all the data which were taken as input via the form will be formatted, and hence, an issue will be opened up.

**Additional context**
According to my opinion, adding such a feature can bring some more worth to the collection we'll have of such open-source events happening across the globe.

**Comment by parthpandyappp** [comment]
Hii @ruchikamuddinagiri, what type of information is expected further?

**Comment by raks924** [comment]
I am a GSSOC'21 participant. I think i can fix this assue . Kindly assign this issue to me.

**Comment by ruchikamuddinagiri** [comment]
> Hii @ruchikamuddinagiri, what type of information is expected further?

Hi, how would you implement the form? Will it be linked to a new webpage? Have assigned this issue to you. You may start working on it and make a PR.

**Comment by parthpandyappp** [comment]
Yes @ruchikamuddinagiri It'll be linked to a new webpage. Well, I'm planning things! Do you have any suggestions?

**Comment by subhangi2731** [comment]
@AkshaySharma008 please assign me this
