### ISSUE TITLE
Problem in dark mode section in the website

### ISSUE THREAD

**Issue by abhijeet141** [DSC-JSS-NOIDA/foss-events#192]
**Describe the bug**
There is a problem in dark mode section as on clicking on dark mode the background is not getting dark only the search bar is getting dark and the fonts are becoming lighter

**To Reproduce**
1. Go to the website
2. Click on dark mode button
3. See the error

**Expected behavior**
After clicking on dark mode the background should have gone dark and the fonts should be clearly visible

**Screenshots**
![image](https://user-images.githubusercontent.com/67696867/111881021-9f15a500-89d4-11eb-995c-9cb3e1130145.png)

**Comment by abhijeet141** [comment]
Hey, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by ruchikamuddinagiri** [comment]
There is another PR #159 on Dark Mode, which will hopefully fix this issue.

**Comment by abhijeet141** [comment]
Thank You for assigning this to me 🙂

**Comment by Inventor77** [comment]
@abhijeet141  Are you still Working on this issue ?
