### ISSUE TITLE
Searching by name must have the exact spelling

### ISSUE THREAD

**Issue by osamamagdy** [DSC-JSS-NOIDA/foss-events#195]
Hey, I am a GSSoC 2021 participant and I would like to fix the bug described below so can anyone assign it to me?

**Describe the bug**
When you search for an event by name it must contain the same spelling or at least the same substring for example if we have an event that contains the word javascript and in the search bar we typed java script instead we won't be able to see the event at all.

**To Reproduce**
1. Go to the search bar
2. type the name of any existing event but with a simple difference in spelling
3. See that the event won't appear at all.

**Expected behavior**
Events with all similar names should appear
**Screenshots**
![Screenshot (750)](https://user-images.githubusercontent.com/59124937/111887419-9fff0480-89dd-11eb-9935-6fc1983fb38a.png)
![Screenshot (751)](https://user-images.githubusercontent.com/59124937/111887423-a7261280-89dd-11eb-9759-a66eaa03ada5.png)

**Comment by osamamagdy** [comment]
@deshraj @spyshiv @sehgalayush1 @singhsterabhi could you assign this to me as a GSSoC 2021 participant?

**Comment by subhangi2731** [comment]
@AkshaySharma008 can u please assign me tgis

**Comment by osamamagdy** [comment]
@AkshaySharma008 I created a pull request that will close this issue like more than Month ago but no one reviewed it
