### ISSUE TITLE
Welcome to DSC HackFest 2020

### ISSUE THREAD

**Issue by PragatiVerma18** [DSC-JSS-NOIDA/foss-events#20]
Hello, Everyone ✨🙌

Thanks for showing your interest in being a part of the **DSC HackFest'2020** 💥

We are super delighted to have you onboard on **Foss Events Website** 🙌

Here are the Mentors for the Project: 

| Name :technologist:   |      Social Media :globe_with_meridians:  |  Github :octocat:  |
|----------|:-------------:|------:|
| Naman Shankhydhar | [LinkedIn](https://www.linkedin.com/in/naman360) |  [Github](https://github.com/naman360) |
| Ayush Tiwari | [LinkedIn](https://www.linkedin.com/in/ayush-tiwari-b376b5194/) |  [Github](https://github.com/servermonk) |
| Pragati Verma | [LinkedIn](https://www.linkedin.com/in/PragatiVerma18/) |  [Github](https://github.com/PragatiVerma18) |

Here are 8 Rules, you should be following while contributing to open-source to make your contributions shine during the whole process:
- Be Nice, Be Respectful to everyone.
- Make proper commit messages and document your Pull Request well.
- Always add comments in your code and explain it to the point.
- Squash your commits before you push them.
- Always create a Pull Request from a Branch; Never from the Master.
- Follow proper Code conventions. 
- Issues would be served on a "First Come, First Serve" basis.
- Code would be reviewed by Mentors before they are merged. Every Pull Request requires 2 Reviews.

<b>Regards,</b>
<i>DSC-JSS-NOIDA (@DSC-JSS-NOIDA)</i> 🤗

**Comment by OmkarPh** [comment]
hi there, I don't know about this DSC hackfest, could you share me any link or booklet regarding the event, I am eager to participate in such events
