### ISSUE TITLE
Adding meta tag with attribute http-equiv content-type

### ISSUE THREAD

**Issue by Diksha-11** [DSC-JSS-NOIDA/foss-events#200]
I would like to add a meta tag containing attribute "http-equiv" and "content-type" in /index.html.

As "http-equiv" attribute set is similar to the http header. Thus, it should be there in the Foss-events.
Along with that "http-equiv" with "content-type" allows us to specify the media type and character set.

Thus, I request maintainer to please /assign me this issue.

~ @rudrakshi99

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue? @ruchikamuddinagiri

**Comment by ruchikamuddinagiri** [comment]
> Hi i am a gssoc participant , can i work on this issue? @ruchikamuddinagiri

This issue has already been assigned. Please look for some other issue that you might be interested in. Happy contributing!.
