### ISSUE TITLE
frontend-dark theme modification

### ISSUE THREAD

**Issue by ShrastiPachauri** [DSC-JSS-NOIDA/foss-events#202]
In the dark theme content of the events are not readable.

I want to change the look in the dark theme so that it becomes readable and user-friendly.

So I request the maintainer to please assign this task to me.
@rudrakshi99

**Comment by AkshaySharma008** [comment]
Hey @ShrastiPachauri, already one participant is working on the same issue. Connect with either Abhijeet or check issue #192, if you think you are doing other things than what is there in this PR, then do mention it here, I will be happy to move ahead.

**Comment by ShrastiPachauri** [comment]
ok ......I will try to figure out if I could contribute to a different issue
