### ISSUE TITLE
Make the whole div clickable

### ISSUE THREAD

**Issue by DhairyaDutt** [DSC-JSS-NOIDA/foss-events#204]
**Describe the solution you'd like**
On clicking the entire div OR 'more info' button, the action will be taken

**Comment by DhairyaDutt** [comment]
@ruchikamuddinagiri If this feature useful for the site, kindly assign it to me. Peace out.

**Comment by ruchikamuddinagiri** [comment]
Hi, this feature has already been implemented as per my knowledge. Please look for other issues that you can contribute to.
