### ISSUE TITLE
Update readme for a particular format of start dates and end dates to be added in events.json

### ISSUE THREAD

**Issue by tend2infinity** [DSC-JSS-NOIDA/foss-events#205]
**Referring to issue #170**
The start dates and end dates for any event should be strictly in dd/mm/yyyy format so that the filter as referred in issue #170 should work. Moreover, this is like a standard format for writing dates, so I would like to include that in readme.
Please assign this issue to me, I am a GSSOC participant.

**Comment by tanviweb19** [comment]
please assign this work to me

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?
