### ISSUE TITLE
Updating information about Google Season Of Docs in events.json file 

### ISSUE THREAD

**Issue by Ayushee11** [DSC-JSS-NOIDA/foss-events#206]
Adding information regarding Google Season Of Docs,its timeline,mode and organizations.
Please assign this issue to me.
@ruchikamuddinagiri @AkshaySharma008

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by Muskan-creator** [comment]
I would like to work on this issue.Please assign it to me

**Comment by Ayushee11** [comment]
@ruchikamuddinagiri please check #223

**Comment by tanviweb19** [comment]
please assign this to me,I would like to work

**Comment by samikshaswayambhu** [comment]
I would like to work on it. I am a GSSOC participant. Please assign me this issue.
