### ISSUE TITLE
Changing navbar to mobile friendly screens

### ISSUE THREAD

**Issue by gayatri517** [DSC-JSS-NOIDA/foss-events#207]
I want to change the navbar to mobile friendly screens as well that is, when the screen gets shorter in size instead of the navbar just showing the contents as it, I want to make them toggle when the screen reduces in size.
Like this-
![navbar](https://user-images.githubusercontent.com/70585276/112031912-dc5b6d80-8b61-11eb-97de-2bda3da7c794.png)

I want to work on this issue as a participant of GSSOC'21.Please assign it to me.
Thank you.

**Comment by ruchikamuddinagiri** [comment]
Hi @gayatri517, thanks for the issue but since there is just a dark/light mode toggle on the navbar currently, a toggle for the navbar does not seem necessary. Please look for other issues that you might be interested in. Happy contributing!
