### ISSUE TITLE
Adding Authentication

### ISSUE THREAD

**Issue by Alenjojo** [DSC-JSS-NOIDA/foss-events#212]
**Is your feature request related to a problem? Please describe.**
By adding an Authentication it would be useful for user to make their own account and show respective events. Not only that the
datas can be stored in cloud

**Describe the solution you'd like**
Firstly i think i'll add firebase Authentication

**Describe alternatives you've considered**
Or else i can add MonogoDB to it

Kindly assign me with this issue

**Comment by ruchikamuddinagiri** [comment]
Hi, there is backend branch of the repository. Please go through it and raise an issue for any features/improvements.
