### ISSUE TITLE
Make modifications in title of event 

### ISSUE THREAD

**Issue by Muskan-creator** [DSC-JSS-NOIDA/foss-events#215]
The title of event described in event cards looks boring.We can change its appearence  to make it look  more attractive which is responsive to event card .

**Comment by Muskan-creator** [comment]
Please assign this issue to me

**Comment by Muskan-creator** [comment]
Thanks for assigning

**Comment by AkshaySharma008** [comment]
Hey @Muskan-creator, please explain what you have done and attach a screenshot of the UI Changes which you have developed.

**Comment by Muskan-creator** [comment]
I have chanced the title showing on event card.IT changes its color and size on hover effect.I have created a PR 
![fossevents](https://user-images.githubusercontent.com/59757988/112477741-532e7b80-8d99-11eb-9eda-8148ae9dd0bb.png)
