### ISSUE TITLE
BACKEND FRONTEND INTEGRATION

### ISSUE THREAD

**Issue by AkshaySharma008** [DSC-JSS-NOIDA/foss-events#216]
**Is your feature request related to a problem? Please describe.**
At present, we have 2 branches, i.e Master(Frontend) and Backend branch differently. The hosted URL contains only the frontend part, i.e. it's static right now. 
While on the other hand, we have another branch Backend, which contains few APIs and other requirements.
I want to make this a dynamic 3 tier application in which backend and frontend are connected and working together.

**Describe the solution you'd like**
The solution would be very simple, You have to connect both ends so that all the requests from Frontend call our backend server and fetch the details instead of JSON stored in Frontend.

**THIS FEATURE NEEDS TO BE IMPLEMENTED IN NEW BRANCH NAMED "FULL-STACK" SO THAT THERE WILL NOT BE ANY CONFLICTS IN FRONTEND & BACKEND BRANCHES**

In case of any doubts, connect with @AkshaySharma008 @PragatiVerma18.

**Comment by K-jais** [comment]
We can use MongoDB database in the backend and in that we will make a events schema which will store the details of events just like in json file and when the database is created we can fetch the data dynamically from database in the backend server.

**Comment by AkshaySharma008** [comment]
Hey @K-jais, this all thing is already developed in our backend branch, Have a look. I am more interested in integrating both of them.

**Comment by K-jais** [comment]
In integrating the frontend and backend we will still use live-server or we will then shift to Nodejs in running it as Nodejs, Expressjs, and MongoDB works efficiently together.

**Comment by AkshaySharma008** [comment]
Yes very true, We will be using NodeJS for the backend part. Have a look at the code of the backend branch.

**Comment by K-jais** [comment]
If we can merge the code from the frontend and backend in another branch and then just use the Ejs file in place of the HTML file and then render that Ejs file in that route, then we can integrate it.

**Comment by K-jais** [comment]
Is it possible, if we can use a file from another branch or we have to merge the two branches in another branch?

**Comment by A7abhilash** [comment]
@AkshaySharma008  Please refer the issue #66 , I had already asked to migrate to react for better performance...

**Comment by A7abhilash** [comment]
> If we can merge the code from the frontend and backend in another branch and then just use the Ejs file in place of the HTML file and then render that Ejs file in that route, then we can integrate it.

Does this really gonna work?? Just curious to know....

**Comment by K-jais** [comment]
> > If we can merge the code from the frontend and backend in another branch and then just use the Ejs file in place of the HTML file and then render that Ejs file in that route, then we can integrate it.
> 
> Does this really gonna work?? Just curious to know....

Yes, it will work. Till now I have used this technique only in my projects to integrate frontend with backend.

**Comment by K-jais** [comment]
> > > If we can merge the code from the frontend and backend in another branch and then just use the Ejs file in place of the HTML file and then render that Ejs file in that route, then we can integrate it.
> > 
> > Does this really gonna work?? Just curious to know....
> 
> Yes, it will work. Till now I have used this technique only in my projects to integrate frontend with backend.

Sir may I proceed with this intent?

**Comment by K-jais** [comment]
Sir @AkshaySharma008 should I proceed with this idea ?

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by K-jais** [comment]
@AkshaySharma008 sir now can I proceed with this?

**Comment by subhangi2731** [comment]
@AkshaySharma008 please assign me this
