### ISSUE TITLE
hover effect on the github logo

### ISSUE THREAD

**Issue by oneknucklehead** [DSC-JSS-NOIDA/foss-events#220]
**Describing the bug**
The Github Logo on the top right corner does not have a hover effect on it

**Comment by oneknucklehead** [comment]
/assign 
Can I get assigned to this issue under GSSoC'21?

**Comment by Nishayadav-bit** [comment]
hey @oneknucklehead 
I would like to work on this issue . please assign to me .
I'm a participant in GSSOC'21.

**Comment by simranbhalla3** [comment]
Hii, I am gssoc participant , could you please assign me this issue?

**Comment by Kritika495** [comment]
I would like to contribute on this issue. Please assign it to me

**Comment by chiragasawa** [comment]
i would like to work on this please assign me.

**Comment by ashish009kum** [comment]
I am ready to work on this issue please assign it to me

**Comment by Sandi-09** [comment]
Can i work on this issue
