### ISSUE TITLE
Events are not showing

### ISSUE THREAD

**Issue by iampranavdhar** [DSC-JSS-NOIDA/foss-events#222]
Hey!
The events are not being rendered on the website when I run in locally by doing `npm start`.Can you look into it and if possible assign it to me I would like to work on it.
Thanks.

**Comment by ruchikamuddinagiri** [comment]
Hi,
It is working fine on my setup. Please attach screenshots of any errors that you might be getting.

**Comment by iampranavdhar** [comment]
Now it's solved previously, Events are not being displayed on the web page there is an error in the JSON file, so events are not being fetched it's a small error.
