### ISSUE TITLE
Adding  some smooth and clear Animations to Theme(Dark and Light mode ) Toggle button 

### ISSUE THREAD

**Issue by Inventor77** [DSC-JSS-NOIDA/foss-events#227]
**The Problem**
On larger Screen Resolution  Components of navigation bar is smaller specifically toggle button and not clear and smooth animation while toggling theme 

**The solution**
I can resize the navbar components also fixing the size ratio problem and can add more defining animation

**Additional context**
Can Mentors overlook on this and feels worth changing  Please assign me this issue and labeling it with gssoc21 
![Screenshot (555)](https://user-images.githubusercontent.com/62959484/112471009-5cb3e580-8d91-11eb-8535-4589d9d7cf32.png)

**Comment by romasinha** [comment]
I have an idea how to go about this, can I work on this issue?

**Comment by Inventor77** [comment]
> I have an idea how to go about this, can I work on this issue?

**Comment by Inventor77** [comment]
@ruchikamuddinagiri  mam points for this PR is not added please can you assign level to it.
