### ISSUE TITLE
To Provide required links to mail and location in Contact Us Section

### ISSUE THREAD

**Issue by SrishtiSingh2001** [DSC-JSS-NOIDA/foss-events#228]
**Is your feature request related to a problem? Please describe.**
There is no link attached to contact us section in footer so that on one click user is prompted to send mail and can go to the site of DSC JSS Noida respectively. 

**Describe the solution you'd like**
This is to add desired links to mail and location in contact us section to make required navigation easier on a single click.

**Comment by unnati914** [comment]
Please assign this issue to me

**Comment by tanviweb19** [comment]
@SrishtiSingh2001 please assign this issue to me

**Comment by Nirpendra09** [comment]
I want to work on this as a gssoc'21 participant. Kindly assign it to me

**Comment by SrishtiSingh2001** [comment]
/assign
I myself is a GSSOC'21 Participant. Mentors, kindly assign this issue to me which I had opened under GSSOC.

**Comment by SrishtiSingh2001** [comment]
@ruchikamuddinagiri @AkshaySharma008

**Comment by ruchikamuddinagiri** [comment]
Hi, this feature has been added now, under another issue. Kindly checkout other issues you might be interested in.

**Comment by simranbhalla3** [comment]
Hiii, I am a gssoc participant , Could you please assign me this issue?

**Comment by SrishtiSingh2001** [comment]
In contact us section, I want to add links to the mail and location, so that on one click user is prompted to send mail and can go to the site of DSC JSS Noida respectively. 
Kindly assign this to me. @ruchikamuddinagiri

**Comment by ruchikamuddinagiri** [comment]
Sure. Please change the issue description and title.

**Comment by SrishtiSingh2001** [comment]
Yes, Sure. Thank You!

**Comment by raks924** [comment]
can i work on this issue?
