### ISSUE TITLE
Improving navbar 

### ISSUE THREAD

**Issue by kumarishalini6** [DSC-JSS-NOIDA/foss-events#232]
I have seen someone is creating home page , about us page so i guess there should be direct link to that page in navbar
and navbar should be more attractive according to project. i would like to work on this issue can you assign this to me under GSSoC'21.

**Comment by AkshaySharma008** [comment]
@kumarishalini6 can you please send some design around this?

**Comment by kumarishalini6** [comment]
yes i can ,but it's better if i take a look on homepage then according to homepage we should work on navbar's colors ,style etc.

for now i was thinking about this design :-
relax it just a sample , here in left there is a navbar which is controlled by right button . 


![COFFEE WORKSHOP ](https://user-images.githubusercontent.com/69043944/112738334-daedc480-8f16-11eb-8e39-912df850d313.png)

**Comment by kumarishalini6** [comment]
if you want something more intresting ,or some other style just tell me.

**Comment by bajajanjana** [comment]
I am a Gssoc'21 participant. I want to improve navbar by adding following features to it.
• Bouncing effect in navbar - on scrolling, navbar disappears for a while and then visible again. It's like navbar bounces upside and then again visible and becomes sticky. I'll be doing this using javascript.
• Improvement in font and styling of website name in navbar that is "FossEvents".
• Addition of hover effect in github logo.
@rudrakshi99 @AkshaySharma008 @ruchikamuddinagiri  please assign this issue to me.

**Comment by AkshaySharma008** [comment]
@kumarishalini6 have you started working on it? I am not clear with what you want to build, can you explain, else @bajajanjana want to contribute so I can assign it to her.

**Comment by kumarishalini6** [comment]
Yes I am working on it I will send you the  sample by tomorrow

**Comment by kumarishalini6** [comment]
I was thinking of side navbar which is controlled by the right navbar menu and try to add some effects

**Comment by AkshaySharma008** [comment]
As of now, we won't be going with the side bar, just work on the same navbar and toggle in the phone. That would be enough.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
i have send PR kindly check

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
