### ISSUE TITLE
Adding functional links in contact us section

### ISSUE THREAD

**Issue by ruchikamuddinagiri** [DSC-JSS-NOIDA/foss-events#234]
**Is your feature request related to a problem? Please describe.**
Adding functional links to the contact us section. Currently, the contact us section links are non-clickable (p tags) and while some of them have the a tag, they are not functional.

**Describe the solution you'd like**
Replace p tags with a tags wherever required. Add corresponding links to them(in href). When they're clicked, they should open up another tab on the browser.

This is an easy issue. All participants are encouraged to contribute to this.

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nishayadav-bit** [comment]
Hey ! i would like to work on this issue please assign to me .
I'm a participant in GSSOC'21.

**Comment by Muskan-creator** [comment]
I want to work on the issue please assign it to me as a gssoc contributor

**Comment by SrishtiSingh2001** [comment]
@ruchikamuddinagiri  I have already added functionality links to mail and site under issue #228  , kindly assign this issue to me to add functionalities in all social media handles just like I did in mail and site.

**Comment by abhijeet141** [comment]
Hi @SrishtiSingh2001 actually @ruchikamuddinagiri has already assigned this issue to me and i will start working on it as soon as i get all the links which i have to add in all social media handles
