### ISSUE TITLE
Adding 9 events in events.json

### ISSUE THREAD

**Issue by K-jais** [DSC-JSS-NOIDA/foss-events#235]
The 9 events are,

1)Digital Ocean Hacktoberfest
2)Season of KDE
3)Open Mainframe Project Mentorship Program
4)Linux Kernel Mentorship Program
5)Redox OS Summer of Code
6)Mozilla Winter of Security
7)Hyperledger Mentorship Program
8)Open Summer of Code
9)Script Winter of Code

**Comment by simranbhalla3** [comment]
Hii , I am a gssoc participant, can you assign this issue to me? I would love to work on this

**Comment by Kritika495** [comment]
I am interested on working on this issue. Please assign it to me

**Comment by AkshaySharma008** [comment]
@simranbhalla3 assigning this issue to you. Please check and try to complete it soon.
@Kritika495 please check any other issue, as this is a very basic issue and didn't need more people to spend time upon.

**Comment by K-jais** [comment]
@AkshaySharma008 sir I have raised this issue so technically should it be assigned to me?

**Comment by K-jais** [comment]
> @AkshaySharma008 sir I have raised this issue so technically shouldn't it be assigned to me?

Just asking sir..

**Comment by AkshaySharma008** [comment]
@K-jais  Really sorry for the misunderstanding. Please proceed.

**Comment by K-jais** [comment]
> @K-jais  Really sorry for the misunderstanding. Please proceed.

Yaa sir no problem.
Thank you sir for assigning me this issue.

**Comment by simranbhalla3** [comment]
> @K-jais Really sorry for the misunderstanding. Please proceed.

I actually started working on this. so now should I drop it?

**Comment by AkshaySharma008** [comment]
@simranbhalla3 connect with @K-jais and work together. 

Open source is more about collaboration. Hope it will work.

**Comment by K-jais** [comment]
> @simranbhalla3 connect with @K-jais and work together. 
> 
> Open source is more about collaboration. Hope it will work.

Yes, it can be done . 
I will pull the request for first 5 events and @simranbhalla3 can pull the request for last 4 or more if she know other events as well.

Is it okay with you @simranbhalla3 ?

**Comment by simranbhalla3** [comment]
> > @simranbhalla3 connect with @K-jais and work together.
> > Open source is more about collaboration. Hope it will work.
> 
> Yes, it can be done .
> I will pull the request for first 5 events and @simranbhalla3 can pull the request for last 4 or more if she know other events as well.
> 
> Is it okay with you @simranbhalla3 ?

Yeah sure! I will work on the last 4 . Thanks for co-operating

**Comment by AkshaySharma008** [comment]
Good to see the amazing open-source spirit. Looking forward to your wonderful collaboration from both of you.

**Comment by simranbhalla3** [comment]
@K-jais Do you have details regarding open summer of code and regarding the application period of hyperledger and script winter of code?

**Comment by K-jais** [comment]
I have information regarding the Open Summer of Code. But I don't have the information regarding the other two.

{
    "title": "Open Summer of Code",
    "website": "osoc.be/",
    "start": "01/07/2021",
    "end": "31/07/2021",
    "organisation": "Open Knowledge Belgium, Hack Your Future, ID Lab, CogniZone and many more ",
    "location": "Online"
  }
