### ISSUE TITLE
Changing "Select Event Status" to "All" in Status

### ISSUE THREAD

**Issue by Alenjojo** [DSC-JSS-NOIDA/foss-events#241]
**Describe the bug**
In the status drop down there's only an option to check out offline or online and not both. Instead users will have to click "Select Event Status" which could be really confusing for them.

**To Reproduce**
1. Go to 'Top Navigation bar'
2. Click on 'Status'
4. So as you can see instead of Select Event Status it can be changed to All

**Expected behavior**
It does the same functionality but it will be much more user friendly

**Comment by AkshaySharma008** [comment]
@Alenjojo assigning you, please update after completing this issue.
