### ISSUE TITLE
feat: Adding Search Icon

### ISSUE THREAD

**Issue by iampranavdhar** [DSC-JSS-NOIDA/foss-events#242]
Hey!
I am Pranavdhar. I would like to add a search icon in the search bar in the search box which looks more appealing and good interactivity for the users.
Thanks

**Comment by AkshaySharma008** [comment]
Please complete it as soon as possible and send a screenshot of your work and raise PR. All the best.

**Comment by iampranavdhar** [comment]
Hey @AkshaySharma008,
I had solved the issue and had sent a pull request. Hope you have seen it.Thank you for assigning it to me.
Thanks
