### ISSUE TITLE
To make the static info clickable in the contact us section  

### ISSUE THREAD

**Issue by DhairyaDutt** [DSC-JSS-NOIDA/foss-events#243]
**Describe the solution you'd like**
I'll make the phone number, gmail, and the location clickable so that it will be more detailed and helpful to the user to contact.

**Comment by ashish009kum** [comment]
what we actually need to do in this can you please explain a little bit more?

**Comment by vaibhavihaveri** [comment]
Hello i am interested  to work on this issue can u assign me

**Comment by Sandi-09** [comment]
Can u assign this issue to me
