### ISSUE TITLE
Add events to events.json

### ISSUE THREAD

**Issue by anisha1208** [DSC-JSS-NOIDA/foss-events#257]
Hey! I am a GSSOC participant.
I wish to add the following events to the ones listed in events.json :

1. **CrossWoc** : CrossWoC is a six-week long opensource event organised by IEEE DTU & IEEE DTU CS.
2. **DevOps India Summit 2021** : The largest DevOps conference in India.
3. **Google Summer of Earth Engine** :  Research program for Indian university students & researchers, based on the Google Summer of Code model.
4. **Open Mainframe Project Mentorship Program** : Mentorship Program to learn valuable mainframe skills and help improve the state of Linux and Open Source on Mainframe development community.
5. **GUADEC** : GNOME community’s largest conference.
6. **SOCIS – The ESA Summer of Code in Space** : Programme that aims at promoting open-source space-related software to students.
7. **Season of KDE** : Both code and non-code projects that benefits the KDE ecosystem.
8. **OpenTechSummit Europe** : Brings together students, developers, companies, and FOSS communities in the open source ecosystem.

**Comment by AkshaySharma008** [comment]
Few of the events are already available so do check out and check that there won't be any repetition. I am assigning this to you. All the best.

**Comment by mansijain980** [comment]
@AkshaySharma008 as it is not solved till now . Please assign this to me .
Thanks.
