### ISSUE TITLE
feat: Adding Hover Effects For Navbar Elements

### ISSUE THREAD

**Issue by iampranavdhar** [DSC-JSS-NOIDA/foss-events#259]
Hey!
I am Pranavdhar. I had seen all the components are having all the hover effects except those in the navbar. So can we add hover effects to the Navbar elements too?. If you wanna add this please assign it to me =.

### Snapshots:

![image](https://user-images.githubusercontent.com/73348574/112943225-d9a6dc80-914e-11eb-8e1f-00bed7d0fc73.png)

![image](https://user-images.githubusercontent.com/73348574/112943256-e3304480-914e-11eb-9aeb-1924c423f0e9.png)

Thanks.

**Comment by Ananyaagupta** [comment]
can i work with @iampranavdhar on this issue?

**Comment by vedant-jain03** [comment]
I want to work in this issue Please assign me

**Comment by NipuniKodithuwakku** [comment]
can I work on this issue as GSSOC21 participant?
