### ISSUE TITLE
Create a logo for Foss-Events

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#26]
**Is your feature request related to a problem? Please describe.**
We currently don't have a logo, so we would love if contributors design a logo for the website.

**Additional context**
Logo should be made/design by contributors, we would know if it is copied.

**Comment by anonymous-31** [comment]
I would like to design it and do my best!!

**Comment by ShashankRawatgit92** [comment]
i have previous experience in making logos pls gassihn thsi to me

**Comment by naman360** [comment]
Go ahead , best logo will be used in the website.
