### ISSUE TITLE
Adding "About us" section for making the site for informative

### ISSUE THREAD

**Issue by DhairyaDutt** [DSC-JSS-NOIDA/foss-events#260]
**Describe the solution you'd like**
Add "About us" section to the site, and add "About us", "events", and "contact us" to the navbar which will make the site more detailed.

**Comment by DhairyaDutt** [comment]
@AkshaySharma008 assign it to me if relevant.

**Comment by vaibhavihaveri** [comment]
I will work on this issue Assign me.
