### ISSUE TITLE
Content not aligned Properly.

### ISSUE THREAD

**Issue by Naman-1234** [DSC-JSS-NOIDA/foss-events#265]
**Is your feature request related to a problem? Please describe.**
The frontend is looking quite good, But the Text Part (In the screenshot) is looking iregular aligned.
![Screenshot (44)](https://user-images.githubusercontent.com/63748249/113059729-6abc9880-91cd-11eb-8f1d-389dbc9ebcb8.png)

**Describe the solution you'd like**
Proper alignment.
![Screenshot (45)](https://user-images.githubusercontent.com/63748249/113059818-832cb300-91cd-11eb-8c24-fdf429a8f8d4.png)

**Describe alternatives you've considered**
Please refer screenshot in the solution.

**Additional context**
Screenshots already provided.

**Comment by Kavs-123** [comment]
Hey @Naman-1234 
Is this issue resolved?

**Comment by Naman-1234** [comment]
@Kavs-123  Yes, I have solved the issue and will make a PR as soon as I get assigned.
