### ISSUE TITLE
Create a new UI for website

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#27]
**Is your feature request related to a problem? Please describe.**
The website has a basic structure and UI, we want contributors to design a new UI that would make website look professional.

**Comment by Dheeraj-01** [comment]
Hi, can you assign me to this? Thanks :) 😊

**Comment by naman360** [comment]
yaa sure, go ahead!

**Comment by Dheeraj-01** [comment]
should I use a bootstrap framework or not for UI?

**Comment by naman360** [comment]
Yes use anything you want to.

**Comment by pallavithakare28** [comment]
@naman360 I would like to work on this issue.

**Comment by naman360** [comment]
@pallavithakare28 go ahead

**Comment by pallavithakare28** [comment]
@naman360 Thank you and I'll soon make a PR.

**Comment by ChiragBolakani** [comment]
Hey, can I work on this I can work with a few UI components. @naman360
