### ISSUE TITLE
Testimonial page for the website.

### ISSUE THREAD

**Issue by RubenFalcao14** [DSC-JSS-NOIDA/foss-events#273]
I would like to add a testimonial page for the website , which is going to display the feedback of various users.

I'm a GSSOC'21 participant and I would love to work on it.

**Comment by SamikshaSankar** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by anushka-srivastava22** [comment]
Hi I am a gssoc participant. I would love to work upon it so can you assign this issue to me.?
