### ISSUE TITLE
The Event card Expands when hoving over it

### ISSUE THREAD

**Issue by Alenjojo** [DSC-JSS-NOIDA/foss-events#274]
**Describe the bug**
When we hover over the title of the event card it enlarges, but if it is larger than a certain length the card expands and pushes the rest of the cards laying below it.

**To Reproduce**
1. Go to 'the event card'
2. Click on 'Longest Title of the event'
3. See error

**Expected behavior**
It expands all the data inside the particular card and the rest of them beneath it.

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/51394913/113332771-3f59bb00-933f-11eb-9067-496bfa9c77f5.png)

**Comment by ayushjha952** [comment]
@Alenjojo  Are you the project admin this project?

**Comment by vedant-jain03** [comment]
I got your point I also tested this Can I work on this issue?

**Comment by ayushjha952** [comment]
I am not the project admin?

**Comment by ayushjha952** [comment]
That's why I am if it assigned by admin, then I would like to work on this issue.

**Comment by Alenjojo** [comment]
@ayushjha952 I'm not the admin of this project. I thought it didn't look matching to the rest of the cards, that's why i opened this issue regarding this topic. If y'all wanna work might have to ask the admin
