### ISSUE TITLE
When scrolling down, navbar right side is empty

### ISSUE THREAD

**Issue by vedant-jain03** [DSC-JSS-NOIDA/foss-events#280]
**Describe the bug**
When we are scrolling down , right-most side of navbar showing empty space of Scroll bar.

**Screenshots**
![bandicam 2021-04-04 18-40-48-894](https://user-images.githubusercontent.com/76901313/113509846-52ee6700-9575-11eb-8279-ae8389bd05e5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by vedant-jain03** [comment]
Can I work on this I guess I have to change the width or Z-index of navbar

**Comment by AkshaySharma008** [comment]
@vedant-jain03 go ahead. Assigning this to you.

**Comment by vedant-jain03** [comment]
@AkshaySharma008 thankyou for assingning 
Will get back to you with my PR
