### ISSUE TITLE
Adding 3 important missing open source programs in events.json file 

### ISSUE THREAD

**Issue by Hrishita99** [DSC-JSS-NOIDA/foss-events#282]
Hello! I am a gssoc'21 participant and i am willing to add the following 3 open source programs in your list - 
NJACK Winter of Code by IIT Patna
KWoC by Kharagpur Open Source Society, IIT Kharagpur (KOSS)
BOSS – Bountiful Open Source Summer by Coding Blocks
I need your permission to work on this issue so kindly assign it to me.

**Comment by AkshaySharma008** [comment]
Go ahead and complete this @Hrishita99 .
