### ISSUE TITLE
Reporting a bug in the website description 

### ISSUE THREAD

**Issue by Hrishita99** [DSC-JSS-NOIDA/foss-events#283]
Hello! I am a gssoc'21 participant and i would like to report one bug in the description that flashes when we open the website. It's mentioned that we will be listing the names of different open source ORGANISATIONS that exist while what we are actually mentioning are the different open source PROGRAMS that take place around the globe. I need your permission to fix this bug so kindly assign this issue to me :)

**Comment by AkshaySharma008** [comment]
@Hrishita99, I have assigned you, please proceed. In case, if you need any help, do mention here.
