### ISSUE TITLE
Improve Navbar 

### ISSUE THREAD

**Issue by meghnabajoria** [DSC-JSS-NOIDA/foss-events#284]
I would like to improve the NavBar. Add Icons for each menu and align them in a more attractive way. Also, I would like to shift the dark mode button to the extreme right as it does not look appropriate when placed in the middle.
@AkshaySharma008 can you assign this issue to me under GSSOC'21.

<img width="1437" alt="Screenshot 2021-04-06 at 12 49 05 PM" src="https://user-images.githubusercontent.com/50470784/113673379-8c8ab380-96d6-11eb-9bfe-6ad4e8f8d235.png">

**Comment by meghnabajoria** [comment]
Hi @AkshaySharma008.Do you want me to make any more changes in the Navbar?
<img width="1437" alt="Screenshot 2021-04-11 at 8 10 00 PM" src="https://user-images.githubusercontent.com/50470784/114308553-015c5400-9b02-11eb-8a5e-6536af967f3f.png">

**Comment by abhijeet141** [comment]
@meghnabajoria Are you still working on this issue else i would like to work on this issue

**Comment by meghnabajoria** [comment]
I have already contributed in this and it has been merged. @AkshaySharma008 can you please close this issue? 
@abhijeet141, maybe you can create another issue on improving navbar and contribute in that. :)
