### ISSUE TITLE
to fix hover effect on card title text

### ISSUE THREAD

**Issue by soulsurya** [DSC-JSS-NOIDA/foss-events#288]
hello,
I'm Suryakant, in your project I want to improve the  hover effect in card's title, it can be improved to make it more beautiful and appealing.
**Current Issue :** whenever we hover over the card's title it enlarges suddenly and also don't look good.

**To Reproduce:**  Go to any [card](https://fossevents.netlify.app/) and hover over it's title.

**Expected Behavior:** is should animate smoothly on hover.

**Comment by soulsurya** [comment]
Please assign me this issue under GSSoC'21 label

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
