### ISSUE TITLE
Improving the search bar UI

### ISSUE THREAD

**Issue by divyanshkhatana** [DSC-JSS-NOIDA/foss-events#292]
Hello, I would like to improve the CSS of the search bar and give it a better look. Also, I would like to rename certain fields like "range start" to "start date" to give a sophisticated look.
@AkshaySharma008 can you assign this issue to me under GSSOC'21.

![image](https://user-images.githubusercontent.com/44130452/114159466-733a6f00-9943-11eb-8a39-820864d91f55.png)

**Comment by raks924** [comment]
can i work on this issue?

**Comment by ambivert-sam** [comment]
@AkshaySharma008 I want to contribute on this issue can I work?

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?
