### ISSUE TITLE
While hovering over the cards it scales out it so much

### ISSUE THREAD

**Issue by shonali2600** [DSC-JSS-NOIDA/foss-events#297]
**Describe the bug**
While hovering over the cards having large event name, it scales out so much that it doesn't look good.

**To Reproduce**
1. Go to 'event cards'
2. hover on the first event name (similar things happens to many other cards too)
3. See the problem

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]

I would like to work on this issue as a gssoc participant, please assign it to me.

**Comment by AkshaySharma008** [comment]
@shonali2600  What kind of solution you are planning for this?

**Comment by shonali2600** [comment]
@AkshaySharma008 I will change its property while hovering. I will change font size on hovering(less than previous one)
