### ISSUE TITLE
Improvement in the events cards

### ISSUE THREAD

**Issue by Khushi-agarwal** [DSC-JSS-NOIDA/foss-events#300]
**Describe the solution you'd like**
The events cards can be improved by the hover effect and flip card animation effect also can be used.

@AkshaySharma008 please assign it to me.

**Comment by AkshaySharma008** [comment]
Flip cards won't look much good, if you think so can you send some samples like images/gifs?

**Comment by Khushi-agarwal** [comment]
@AkshaySharma008 This is the gif of how the flip card would look.Kindly have a look.
![Testimonial](https://user-images.githubusercontent.com/76625662/114413151-5912c200-9bcb-11eb-972b-90981bd45714.gif)
I had made for another project.

**Comment by AkshaySharma008** [comment]
These are not looking good, Our website is quite simple and informative, this looks too slow and funky. As of now, this modification is not needed, if you think you have some good design in your mind then do mention it here. Else try to work on some other issues.
