### ISSUE TITLE
Issue with search bar in mobile mode 

### ISSUE THREAD

**Issue by divyanshkhatana** [DSC-JSS-NOIDA/foss-events#305]
The search bar and text is collapsing in mobile mode 
![image](https://user-images.githubusercontent.com/44130452/114534828-07227880-9c6d-11eb-8cf2-08119cc314be.png)

**Comment by divyanshkhatana** [comment]
@AkshaySharma008 please assign this issue

**Comment by divyanshkhatana** [comment]
@AkshaySharma008  I have completed it please assign me this under gssoc21  .So that I can merge it 
![image](https://user-images.githubusercontent.com/44130452/114540999-cc700e80-9c73-11eb-901f-2421457979b1.png)

**Comment by yash0501** [comment]
@divyanshkhatana  this issue is assigned to you and you  can create a PR on it once the code part is done.

**Comment by divyanshkhatana** [comment]
> @divyanshkhatana this issue is assigned to you and you can create a PR on it once the code part is done.

@yash0501 I have created the PR kindly check

**Comment by AkshaySharma008** [comment]
Successfully Merged, All the best, Keep Contributing.
