### ISSUE TITLE
Add links to footer DSC logo and header fossevents text

### ISSUE THREAD

**Issue by tarunsinghofficial** [DSC-JSS-NOIDA/foss-events#310]
**Describe the bug**
We can add the home page/ Contributing GitHub link to foss events header text and in the footer, we can add a DSC JSS [link](https://www.dscjss.in/) to the image also.

**Comment by raks924** [comment]
hey @ruchikamuddinagiri i would love to work on this issue.Kindly assign it to me.

**Comment by Sowmya-Betina** [comment]
hey @ruchikamuddinagiri, can you please assign this to me
