### ISSUE TITLE
Improve menu icons on NavBar

### ISSUE THREAD

**Issue by meghnabajoria** [DSC-JSS-NOIDA/foss-events#314]
Previously, I improved the layout of the Navbar. I wish to use better menu icons in the Navbar. 
@AkshaySharma008  please assign this issue to me under GSSOC'21.

<img width="1426" alt="Screenshot 2021-04-15 at 12 01 51 AM" src="https://user-images.githubusercontent.com/50470784/114761223-d1b98000-9d7d-11eb-8174-e3d133464ade.png">

**Comment by priyakumari02** [comment]
I am interested in this issue please assign me this issue.

**Comment by meghnabajoria** [comment]
It has already been assigned to me :)

**Comment by priyakumari02** [comment]
Then i cannot contribute in this?
