### ISSUE TITLE
Loading Animation is not Responsive - Mobile View

### ISSUE THREAD

**Issue by AkshaySharma008** [DSC-JSS-NOIDA/foss-events#315]
**Describe the bug**
Loading Animation is not Responsive - Mobile View

**To Reproduce**
1. Go to website link in mobile view (use Chrome Dev Tools)
2. Click on Refresh Page
3. See an error

**Expected behavior**
Loading Animation is not Responsive - Mobile View

**Comment by AkshaySharma008** [comment]
Those who are interested, Please check.

**Comment by ipranshujain** [comment]
I want to work on it. Please assign it to me.

**Comment by ipranshujain** [comment]
Sir I have solved this issue. Can I make PR now?

**Comment by AkshaySharma008** [comment]
@ipranshujain, please proceed and generate a PR.
