### ISSUE TITLE
Search icon is not showing in the search bar

### ISSUE THREAD

**Issue by DhairyaDutt** [DSC-JSS-NOIDA/foss-events#322]
@AkshaySharma008 plz assign this issue to me

**Comment by priyakumari02** [comment]
@AkshaySharma008 I want to contribute into this . Please assign me this issue

**Comment by NipuniKodithuwakku** [comment]
can I work on this issue?

**Comment by raks924** [comment]
hey can i work on this issue?

**Comment by adysis14** [comment]
Hey! I'm interested in solving this issue . I would be very grateful if you assign this iisue to me under GSSOC'21

Thank You!
