### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by dig9074vijay** [DSC-JSS-NOIDA/foss-events#327]
**Is your feature request related to a problem? Please describe.**
I noticed that the site doesn't contain a favicon.

**Describe the solution you'd like**
I'd like to add a favicon as a GSSOC'21 participant.

**Additional context**
<img width="444" alt="Screenshot 2021-04-18 at 7 27 50 AM" src="https://user-images.githubusercontent.com/55308273/115131717-dac57e00-a017-11eb-859f-ca0e23058624.png">

**Comment by NipuniKodithuwakku** [comment]
can I work on this issue?
