### ISSUE TITLE
Improving navbar

### ISSUE THREAD

**Issue by itsij** [DSC-JSS-NOIDA/foss-events#328]
I would like to change the background color of the navbar to green instead of the current color: black. This will enhance the visual appearance of the website. Here it is: 
The visual appeal of green color in navbar is clearly evident.

![image](https://user-images.githubusercontent.com/72145053/115544370-20a46f80-a2c0-11eb-8607-f209689f2461.png)
![image](https://user-images.githubusercontent.com/72145053/115544621-724cfa00-a2c0-11eb-99f6-f796a242c46d.png)

And green navbar is also enhancing the look in dark mode.
Plz assign this issue to me. I would like to work on it as a GSSOC participant. 
@AkshaySharma008 @PragatiVerma18

**Comment by AkshaySharma008** [comment]
@itsij I don't think, it's needed. We have implemented our theme.

**Comment by itsij** [comment]
@AkshaySharma008 I noticed those social media icons as new additions today and still feel that maybe green can suit better. Please give it a look again.

I want to make it look like below attached initial two pictures instead of bottom two pictures.

I have made a change in the color of theme toggle button also in dark theme so that it does not look bad after making the navbar color green.(see photo 2) 

![image](https://user-images.githubusercontent.com/72145053/115715845-2ec4bf80-a396-11eb-9952-ec8fa7192aed.png)
.
.......................................................................................................................................................................................................................................................
.![image](https://user-images.githubusercontent.com/72145053/115718456-bf9c9a80-a398-11eb-9127-6e69e113224e.png)

.
.......................................................................................................................................................................................................................................................
.
![image](https://user-images.githubusercontent.com/72145053/115715985-52880580-a396-11eb-9e89-2ed246b5a853.png)
.......................................................................................................................................................................................................................................................
.
![image](https://user-images.githubusercontent.com/72145053/115717069-739d2600-a397-11eb-8363-87a489a8c20e.png)
