### ISSUE TITLE
Rectifying issue in footer

### ISSUE THREAD

**Issue by itsij** [DSC-JSS-NOIDA/foss-events#330]
In the footer, this is written: "Made with ❤ By DSC JSSATEN"
But in dark mode, "Made with ❤ By" is barely visible.
![image](https://user-images.githubusercontent.com/72145053/115595936-29636880-a2f5-11eb-879d-81cd159f53b4.png)
   **Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version:  90.0.4430.85

Please assign this issue to me. I would like to work on improving it as GSSOC participant.
@AkshaySharma008 @PragatiVerma18 @ruchikamuddinagiri

**Comment by rudrakshi99** [comment]
This issue is already get solved in #172

**Comment by itsij** [comment]
@AkshaySharma008 though you have merged my PR but still the footer text is not grey. It is red currently because it was made red in issue #172 , just a few hours ago before i made my PR. using a different class selector than the one i did
So, shall i make a PR again converting it to grey?
