### ISSUE TITLE
Enhancement in contact-us form

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [DSC-JSS-NOIDA/foss-events#341]
**Describe the bug**
The label and the placeholder in input fields is not aligned properly. I would like to fix that

**To Reproduce**

**Expected behavior**
Proper alignment of label and placeholder

**Screenshots**
![fossevents](https://user-images.githubusercontent.com/58511560/116842784-5cfa9880-abfb-11eb-9622-b3f97d33a26a.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to work on this issue under GSSoC'21

**Comment by mansijain980** [comment]
CAn i work on it?
