### ISSUE TITLE
Improving the Search Bar

### ISSUE THREAD

**Issue by anisha1208** [DSC-JSS-NOIDA/foss-events#348]
Hey I am a GSSoC Participant, and I would like to improve the search bar by making the following changes:

1.  Improve the visibility of the icons (calendar and phone) as well as text in the search bar in the dark mode.
2.  Position it in a better way, and modify border radius.
3. Change the existing Background of the search bar to a gradient that fits with the theme.

Kindly assign me the issue.

Here is my work:

![image](https://user-images.githubusercontent.com/76607578/117570321-3ea70800-b0e7-11eb-8d30-ecc80cc863c3.png)

![image](https://user-images.githubusercontent.com/76607578/117570352-5e3e3080-b0e7-11eb-8bd9-4afb6b088881.png)

**Comment by raks924** [comment]
hey can i work on this issue?
