### ISSUE TITLE
Adding social links

### ISSUE THREAD

**Issue by Yunika-Bajracharya** [DSC-JSS-NOIDA/foss-events#359]
I want to add:
website link: https://dsc.community.dev/jss-academy-of-technical-education-noida/
discord link: https://discord.com/invite/EBgD52V2hM
telegram link: https://t.me/DSCJSSATEN

Please assign me this issue under the ggsoc'21 tag

**Comment by rudrakshi99** [comment]
@Yunika-Bajracharya Go ahead.
