### ISSUE TITLE
Change the navbar to sidebar or navigation drawer

### ISSUE THREAD

**Issue by subhangi2731** [DSC-JSS-NOIDA/foss-events#369]
I will change the navbar to sidebar or navigation drawer

**Comment by subhangi2731** [comment]
@rudrakshi99 please assign this issue to me

**Comment by subhangi2731** [comment]
@AkshaySharma008 please assign me so that I can start working

**Comment by AkshaySharma008** [comment]
Please show your suggestion in the form of Screenshot or Video
