### ISSUE TITLE
adding time clock

### ISSUE THREAD

**Issue by Sowmya-Betina** [DSC-JSS-NOIDA/foss-events#374]
I would like add a timer and clock to make this more feasible and easy to use

**Comment by AkshaySharma008** [comment]
Please describe your Idea with some Images or Illustrations. Or explain it clearly.

**Comment by Sowmya-Betina** [comment]
![Capture](https://user-images.githubusercontent.com/67799074/119227337-fd711800-bb2a-11eb-8880-2fcdb23cc0d8.PNG)

I would like to add a clock to the homepage using HTML functions and time modules for much more easy use
