### ISSUE TITLE
varying card heights.

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#48]
**Describe the bug**
All cards have different heights.

**Expected behavior**
All cards should be of same height.

**Screenshots**
![Screenshot from 2020-10-04 10-11-35](https://user-images.githubusercontent.com/40193621/95007161-0b206e80-062a-11eb-84b4-d89ba2319f5b.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Comment by Atimabh** [comment]
Hey @naman360 I would like to work on this, please assign it to me.
