### ISSUE TITLE
Setup live-server as dev-dependency

### ISSUE THREAD

**Issue by naman360** [DSC-JSS-NOIDA/foss-events#51]
**Is your feature request related to a problem? Please describe.**
For running the website on live-server we need to globally install `live-server`.

**Describe the solution you'd like**
Setup `package.json` and add `live-server` as development dependency, so that when we run `npm install` `live server` gets installed as dependency for `foss-events` directory (not globally).

**Describe alternatives you've considered**
Any more other alternative can be used, but first comment down the alternative you want to use.

**Comment by heysujal** [comment]
@naman360  I would like to work on it.

**Comment by naman360** [comment]
Do you have an alternative or you'll use the listed way?

**Comment by heysujal** [comment]
I will be using the listed one

**Comment by naman360** [comment]
Go ahead!

**Comment by Shruti3004** [comment]
@naman360 I would like to work on it

**Comment by naman360** [comment]
@Shruti3004 Go ahead!
