### ISSUE TITLE
Adding more open source events

### ISSUE THREAD

**Issue by aniketsingh98571** [DSC-JSS-NOIDA/foss-events#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Addition of GSSoC, GSoC, MLH fellowship to the foss website

**Describe alternatives you've considered**

**Additional context**

**Comment by aniketsingh98571** [comment]
@PragatiVerma18 @servermonk , Can I move ahead with this issue for GSSoC 2021?

**Comment by IdealisticINTJ** [comment]
Can I go ahead and contribute to this issue for GSSoC '21?

**Comment by yashsehgal** [comment]
> **Is your feature request related to a problem? Please describe.**
> No
> 
> **Describe the solution you'd like**
> Addition of GSSoC, GSoC, MLH fellowship to the foss website
> 
> **Describe alternatives you've considered**
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Also, What we can do is. We can use APIs of websites like Meetup, Insider and give users, real-time event updates.
What do you think?

**Comment by krishantraj** [comment]
can i contribute in it as a part of GSSoC 2021? i have made a pr though as directed for this issue.

**Comment by aniketsingh98571** [comment]
> can i contribute in it as a part of GSSoC 2021? i have made a pr though as directed for this issue.

this is not a good practice for open source contribution, you must wait for the issues to assign it to you.

**Comment by krishantraj** [comment]
> > can i contribute in it as a part of GSSoC 2021? i have made a pr though as directed for this issue.
> 
> this is not a good practice for open source contribution, you must wait for the issues to assign it to you.

oh I'm really sorry for that , this is  my first pr un aware of the actual procedure, i will keep this in mind in future. will be glad if u can guide me further.

**Comment by Dev-anuj** [comment]
Even am a beginner, for example, there is 4 issues and he assigned 4 issues to 4 people what others can do then?
and what we have to do so they can assign the issue to us only

**Comment by yashikabhargava** [comment]
Can I go ahead and contribute to this issue as a part of GSSoC '21?

**Comment by maanpatel2492** [comment]
> **Is your feature request related to a problem? Please describe.**
> No
> 
> **Describe the solution you'd like**
> Addition of GSSoC, GSoC, MLH fellowship to the foss website
> 
> **Describe alternatives you've considered**
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Okay,If issue assigned to me can I add more than one ?

**Comment by vismitap** [comment]
May I work on this as a part of GSSoC'21 ?

**Comment by naman360** [comment]
You can create PR on this issue without getting assigned as any user can add as many distinct OSS programmes as possible.

**Comment by gaurav24072002** [comment]
Hey !! I have a list of open source programs should I add them ... and yes I am Interested in this issue Please assign it to me under GSSOC '21.

**Comment by janvi01** [comment]
GSSOC '21
Want to add some more open-source program, Glad if it will be assigned to me.

**Comment by padmajabhol** [comment]
Hey, I want to add more open source program. Are we supposed to wait till you assign us or should we make PRs?

**Comment by nabin-nath** [comment]
Hello, I want to add  more open source events.

**Comment by nagasaisriya** [comment]
Hello, would like to add more open source events and contribute as a part of GsSoc

**Comment by Riya764** [comment]
would like to work on this under gssoc'21.

**Comment by GovindCodes** [comment]
I would love to work on this, under GSSOC '21.

**Comment by vidhi1121** [comment]
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me?
