### ISSUE TITLE
Revamp the project using React JS

### ISSUE THREAD

**Issue by A7abhilash** [DSC-JSS-NOIDA/foss-events#66]
**Is your feature request related to a problem? Please describe.**
*As this a pure static site with just outputting the data from events.json file, I could see alot of js code written that manipulates the dom. Also the styling for cards has the property cursor: pointer, but has no onclick event assigned.*

**Describe the solution you'd like**
*I would like to build the same project using React and maintain minimalistic UI using framer motion and bootstrap.*

**Describe alternatives you've considered**
*Even Gatsby JS can be used instead of React JS if it's 100% static.*

**Additional context**
- We can remove the cards dynamically if the end date is over.
- We can let hosts signup and register their event(like open source or any hackathons) and later the team can review the event and approve to display on the website. (We will then need backend also but not a big issue, I can handle the stuff).

#GSSOC21

**Comment by naman360** [comment]
Leave the revamp part but you can go ahead with features listed in additional context.

**Comment by A7abhilash** [comment]
@naman360 The code using vanilla JavaScript would be large for authentication, authorization, redirecting and can be difficult also but it can be done easing using React JS... Also the revamping wouldn't take much time because I've good experience in it and once I get started then we can definitely go ahead with the features mentioned... 
If you still insist me to go ahead without revamping then it would take some time for me to first understand DOM manipulation that's there in getEvents.js and need to plan about authentication(and other stuff).

**Comment by naman360** [comment]
That is not a priority right now, may plan it afterwards but you can go with removing the cards dynamically if the end date is over.

**Comment by A7abhilash** [comment]
@naman360 Okay!!!
But can I change the date to either of the following format??
*Option 1: Fri Mar 05 2021 (Day Month Date Year)*
*Option 2: 03/05/2021 (Month/Day/Year)*
so that it would be easy to manipulate the date in JavaScript

**Comment by A7abhilash** [comment]
> That is not a priority right now, may plan it afterwards but you can go with removing the cards dynamically if the end date is over.

Any thoughts of using ReactJS?
