### ISSUE TITLE
Enhancing the Navbar style.

### ISSUE THREAD

**Issue by Meghna180401** [DSC-JSS-NOIDA/foss-events#70]
**Is your feature request related to a problem? Please describe.**
_I feel the Navbar should be have a little different CSS styling since the Navbar and the name of the site 'FossEvents' is becoming out of focus as compared to the main container body._

**Describe the solution you'd like**
_I would like to implement the following changes to the Navbar using Bootstrap:
    1. Changing the font style, size and centering the name of the site 'FossEvents' 
    2. Increasing the height of the Navbar to accommodate the changes with clarity_

#GSSOC'21

**Comment by vkassingh** [comment]
i am interested to contribute in the foss event project. can you please share discord server or similar for further discussion?

**Comment by Manas502** [comment]
Hey! I'd love to work/collaborate on this issue. Can you please guide me further?

**Comment by avinashjha1320** [comment]
GSSoC'21
I wanted to fix this issue...can you please assign me this issue?

**Comment by Naman-12911** [comment]
I am a participant of girls scripts 
Please me this issue .

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by nagasaisriya** [comment]
Hello, I would like to work on this issue as a part of GsSoc'21.
Could you please assign it?

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this . Hope to hear back from you . 
Thank you .

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. I'm interested to contribute in this issue. Kindly assign me.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by Anshika-Srivastava** [comment]
I am a participant in GSSOC'21. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you!!

**Comment by raveena69** [comment]
Hi,
 I'm a participant in GSSOC'21 and I would like to contribute to this issue.
