### ISSUE TITLE
Centralize All Events On the Main Page

### ISSUE THREAD

**Issue by vieee** [DSC-JSS-NOIDA/foss-events#71]
The Events look quite sidelined when viewed on a normal PC. 
![Screenshot_2021-03-07 Foss Events](https://user-images.githubusercontent.com/47855729/110222764-a0d26980-7efa-11eb-8026-c3d3acd51106.png)

This can be rectified by centralizing them for adequate viewing on all screens (particularly those with high width)

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC.

**Comment by avinashjha1320** [comment]
Hey..I would like to contribute to this issue for GSSoC'21. Can you please assign it to me.

**Comment by somya51p** [comment]
Hey...I would like to contribute to this issue. Can you assign me the same!!

**Comment by gnikita432** [comment]
hey...I would like to contribute to this issue for GSSOC'21. please assign this task to me.
![c2](https://user-images.githubusercontent.com/61223163/110433686-cb791980-80d6-11eb-8fac-8cb9e6506ec6.PNG)
