### ISSUE TITLE
Creating a landing page

### ISSUE THREAD

**Issue by heyankit78** [DSC-JSS-NOIDA/foss-events#73]
It enhances UI/UX

**Comment by avinashjha1320** [comment]
GSSoC'21
Hey, I have a good experience in UI. Can I contribute to this in GSSoC'21?

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by heyankit78** [comment]
I am also a participant of GSSOC 21.So the mentor of this project can assign someone to work on it .
I also want to contribute on it

**Comment by Priyanka7011** [comment]
hii! 
I am a GSSOC 2021 participant.
I have good experience in UI/UX designing . I would love to contribute to this.

Please assign me this.
Thank You

**Comment by vanshikapandey** [comment]
Sir I am interested in contributing to this issue as I have been working as a front end developer. Please assign this to me

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.
