### ISSUE TITLE
2 links on home page are broken

### ISSUE THREAD

**Issue by satcasm** [DSC-JSS-NOIDA/foss-events#74]
**Describe the bug**
2 ``More Info`` links are broken , it seems that there is a typo in the links.

**To Reproduce**
1. Go to https://fossevents.netlify.app/
2. Click on ``More Info`` on GIRLSCRIPT SUMMER OF CODE and Google Summer of Code
3. See error

**Expected behavior**
It should lead to the correct destination.

**Screenshots**
![image](https://user-images.githubusercontent.com/56315878/110335119-865ad600-8049-11eb-8261-0145d2908e0b.png)
![image](https://user-images.githubusercontent.com/56315878/110335283-af7b6680-8049-11eb-8ad5-a4ac1e267b48.png)

**Additional context**
Would like to work on in under GSSOC' 21.

**Comment by robin025** [comment]
i would like to work on this issue

**Comment by avinashjha1320** [comment]
GSSoC'21
I would like to work on it for GSSoC'21. Can you please assign it to me?

**Comment by puja0655** [comment]
Please assign me on this issue

**Comment by padmajabhol** [comment]
I m intrested in solving this issue, please assign me.

**Comment by SainathPoojary** [comment]
Please Assign it to me. I have fixed the bug

**Comment by mansijain980** [comment]
@satcasm I can fix it easily . I was working on it from two days . Please assign it to me . I got the error.

**Comment by satcasm** [comment]
Closing the issue as it seems to be fixed already.
