### ISSUE TITLE
[Backend]: Setup a response handler for the API

### ISSUE THREAD

**Issue by Mayank0255** [DSC-JSS-NOIDA/foss-events#76]
The response handler is a helper function and for that, we can put this under the helper's directory.
The benefit of this is for front-end developers working on this project, for which fetching appropriate data from the endpoint would be easier and well structured.

The Response Handler should be of this structure:

```
{
    success (Boolean): If the data is successfully retrieved then it should be "true", otherwise it should be "false".
    code (Integer): Appropriate status code of the API call like 501 for bad request, 200 for OK, etc.
    message (String): Message describing the action performed like "Post Created Successfully", "Failed to Create the Post", etc.
    data (Object): Return the data in this field if retrieved successfully, otherwise it should be "null"
}
```

Can I work on this?

**Comment by Mayank0255** [comment]
Can you assign this issue to me?
@PragatiVerma18

**Comment by samyakjain10** [comment]
Hey! I want to work on this issue under GSSOC'21. Can you assign this issue to me? @PragatiVerma18
