### ISSUE TITLE
Link for GSOC event is broken

### ISSUE THREAD

**Issue by Aarushi3113** [DSC-JSS-NOIDA/foss-events#81]
**Describe the bug**
The link for the google summer of code is broken and has a typo in it.

**Expected behavior**
The correct link should open the GSOC website 

**Additional context**
I can fix the broken link. Please assign this issue to me under GSSOC'21 label.

**Comment by mansijain980** [comment]
@Aarushi3113 maam , I am a participant of GSSOC'21 . I would like to implement this as i got the error . 
There is some error in events.json file . I can fix the broken link . 
Please assign it to me . 
Thank you
