### ISSUE TITLE
[GSSoC'21] Invalid date format in events.json

### ISSUE THREAD

**Issue by Samridhi-98** [DSC-JSS-NOIDA/foss-events#85]
**Describe the bug**
The date format in events.json is invalid somewhere it is dd/mm/yy and in some sections, it's dd/mm/yy with time.
**To Reproduce**
1. Go to 'foss-event' folder
2. Open the 'frontend' folder
3. Move to 'data/events.json.'

**Expected behavior**
The date format should be **MM/DD/YYYY** in events.json

**Comment by Nikitha2309** [comment]
I am a GSSoC'21 participant and would like to work on this PR. I already added a commit with clean code and understandable comments. Please assign this to me

**Comment by Navya-amarneni** [comment]
Hey !!!! I found this project to be interesting and would like to contribute. I have successfully fixed the bug and have made a PR regarding the invalid date format issue. Kindly have a look and please assign this to me.

This is a screenshot regarding the bug fix solution:
![Screenshot (850)](https://user-images.githubusercontent.com/47153245/110614319-39494200-81b8-11eb-86cb-0bdab18e098e.png)

**Comment by Shraddha13Jain** [comment]
/assign
please assign this issue to me. I want to contribute to it as a participant in GSSoC'21
