### ISSUE TITLE
[GSSOC'21] Add events to events.json file

### ISSUE THREAD

**Issue by ritik307** [DSC-JSS-NOIDA/foss-events#86]
### Description
Since everyone is creating a separate issue regarding adding each and every event. I have created an issue for all the upcoming addition of events so that all the events PR will be located under the same issue and will be easy to review.

### Format for `event.json`
{
  "title": "`TITLE OF THE EVENT`",
  "website": "`WEBSITE OF THE EVENT`",
  "start": "`DATE IN MM/DD/YYYY FORMAT`",
  "end": "`DATE IN MM/DD/YYYY FORMAT`",
  "organisation": "`ORGANISATION NAME`",
  "location": "`ONLINE or OFFLINE MODE`"
}
**Note:** Date should be in `MM/DD/YYYY` format

**Comment by Rutikab12** [comment]
Hey I would love to work on this issue as early as possible. I want to contribute it as GSSoC'21 participant.

**Comment by ritik307** [comment]
@Shraddha13Jain  @Rutikab12  go for it guys.

**Comment by nancyyadav22** [comment]
Hey ! I would like to contribute on this issue as a GSS0C'21 participant. Can you assign this issue to me ?

**Comment by anamkaa** [comment]
I would like to work on this issue as a part of GSSOC'21. Please assign it to me.

**Comment by ritik307** [comment]
@nancyyadav22 @anamkaa @Shraddha13Jain @Rutikab12 please confirm it with the mentors/project admin(@naman360 @PragatiVerma18  @servermonk ) of this project about this issue. I have also tagged them multiple times but they haven't responded yet. If they do so you can work on this issue.

**Comment by Rutikab12** [comment]
> @nancyyadav22 @anamkaa @Shraddha13Jain @Rutikab12 please confirm it with the mentors/project admin(@naman360 @PragatiVerma18 @servermonk ) of this project about this issue. I have also tagged them multiple times but they haven't responded yet. If they do so you can work on this issue.

My PR got merged on this issue before 2 days.

**Comment by ritik307** [comment]
> 
> 
> > @nancyyadav22 @anamkaa @Shraddha13Jain @Rutikab12 please confirm it with the mentors/project admin(@naman360 @PragatiVerma18 @servermonk ) of this project about this issue. I have also tagged them multiple times but they haven't responded yet. If they do so you can work on this issue.
> 
> My PR got merged on this issue before 2 days.

Nice🎉 then you guys are free to work on this issue make sure you don't repeat the events already present in the JSON file. 
Before working make sure you guys mention the event you are working on.

**Comment by Shraddha13Jain** [comment]
please review my PR @ritik307 . I made it 2 days ago.

**Comment by ritik307** [comment]
> 
> 
> please review my PR @ritik307 . I made it 2 days ago.

sorry to say @Shraddha13Jain its not in my hands to review a PR, my PR is also pending. I created this issue so that it would be easier for the project mentors to locate event.json PRs.
Project mentors- @naman360 @PragatiVerma18 @servermonk. Please tag them for merging the PRs.

**Comment by Shraddha13Jain** [comment]
okay thanks @ritik307 .

**Comment by Shraddha13Jain** [comment]
please review my PR @naman360 @PragatiVerma18 @servermonk . I made it 2 days ago.
