### ISSUE TITLE
Events that have already started should show "Offline" instead of "Online"

### ISSUE THREAD

**Issue by MadHawkx** [DSC-JSS-NOIDA/foss-events#88]
If an open-source event is supposed to start on 1/03/2021 and the present date is 2/03/2021. The event should show offline because the registrations are now closed and students can not apply to it. So, it makes more sense to show "Offline" or "Ended". 

Solution-
It can be easily tackled by setting an expiry date as the start date or constantly checking if that day's date is more than the start date.

**Comment by a-abhinav** [comment]
I would like to add this feature please assign me this issue.
