### ISSUE TITLE
[GSSOC'21] Arrange events from most recent to least recent

### ISSUE THREAD

**Issue by ritik307** [DSC-JSS-NOIDA/foss-events#90]
### Description 
The events should be arranged in the format from most recent to the least recent event so that it would be easier for the user to locate and register for the events of their choice.

**Comment by Samridhi-98** [comment]
Working on it will submit the PR by today.

**Comment by mdPial** [comment]
> Working on it.

okay

**Comment by hrushikesh-git** [comment]
Hey @ritik307  i would like to work on this issue as the beginning of GSSOC'21 contribution

**Comment by ritik307** [comment]
@hrushikesh-git thanks for the interest but the PR regarding this issue has already been made.
