### ISSUE TITLE
Improve more info buttons.

### ISSUE THREAD

**Issue by padmajabhol** [DSC-JSS-NOIDA/foss-events#91]
**Is your feature request related to a problem? Please describe.**
Not really, but the existing buttons look boring.

**Describe the solution you'd like**
I want to add animation to the buttons.

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by Naman-12911** [comment]
I want to contribute to this issue. please assign me this issue.

**Comment by Bannump** [comment]
Hey I want to animate the look of the button & also when hovered and clicked on. Waiting for you to assign .

**Comment by 0Faiz0** [comment]
I would like to contribute on this project, on hover i can animate the buttons.
Project admin will you please assign this issue to me.
GSSOC'21
