### ISSUE TITLE
Removing Hacktoberfest 2020 logo from the readme.

### ISSUE THREAD

**Issue by noviicee** [DSC-JSS-NOIDA/foss-events#95]
Since Hacktoberfest 2020 is over so there is no need to having it in the readme and also in the About.
Also lines 137 and 141 of readme file, are not needed now. 
Plus, the link to check contributions for hacktoberfest 2020 is not working, obviously because maintainers have removed the page.
Hence, I would like to clean the readme file and update it as per requirements of current time.  :)

**Comment by jonathanalvares9009** [comment]
Can I work on this issue?

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by sagunjaiswal** [comment]
I would love to work on this issue. 
Can you assign this to me?

**Comment by saloni-15** [comment]
I can work on this issue.

**Comment by noviicee** [comment]
> Thanks for opening this issue, a maintainer will get back to you shortly!

When? 😓
